import { type EventFlag } from './types'

export const eventFlags: EventFlag[] = [
  {
    name: 'Playthrough Complete: Age of Stars',
    id: 21,
    category: 'ending',
  },
  {
    name: 'Playthrough Complete: Lord of the Frenzied Flame',
    id: 22,
    category: 'ending',
  },
  {
    id: 10000800,
    name: 'Godrick the Grafted',
    category: 'boss',
    location: 'Stormveil Castle',
  },
  {
    id: 10000850,
    name: 'Margit, the Fell Omen',
    category: 'boss',
    location: 'Stormveil Castle',
  },
  {
    id: 10010800,
    name: 'Grafted Scion',
    category: 'boss',
    location: 'Chapel of Anticipation',
  },
  {
    id: 11000800,
    name: 'Morgott, the Omen King',
    category: 'boss',
    location: 'Leyndell, Royal Capital',
  },
  {
    id: 11000850,
    name: 'Godfrey, First Elden Lord (Golden Shade)',
    category: 'boss',
    location: 'Leyndell, Royal Capital',
  },
  {
    id: 11050800,
    name: 'Godfrey, First Elden Lord / Hoarah Loux, Warrior',
    category: 'boss',
    location: 'Leyndell, Ashen Capital',
  },
  {
    id: 11050850,
    name: 'Sir Gideon Ofnir, the All-Knowing',
    category: 'boss',
    location: 'Leyndell, Ashen Capital',
  },
  {
    id: 12010800,
    name: 'Dragonkin Soldier of Nokstella',
    category: 'boss',
    location: 'Ainsel River',
  },
  {
    id: 12010850,
    name: 'Dragonkin Soldier (Lake of Rot)',
    category: 'boss',
    location: 'Lake of Rot',
  },
  {
    id: 12020800,
    name: 'Valiant Gargoyles',
    category: 'boss',
    location: 'Nokron, Eternal City',
  },
  {
    id: 12020830,
    name: 'Dragonkin Soldier (Siofra River)',
    category: 'boss',
    location: 'Siofra River',
  },
  {
    id: 12020850,
    name: 'Mimic Tear',
    category: 'boss',
    location: 'Nokron, Eternal City',
  },
  {
    id: 12030390,
    name: 'Crucible Knight Siluria',
    category: 'boss',
    location: 'Deeproot Depths',
  },
  {
    id: 12030800,
    name: "Fia's Champions",
    category: 'boss',
    location: 'Deeproot Depths',
  },
  {
    id: 12030850,
    name: 'Lichdragon Fortissax',
    category: 'boss',
    location: 'Deeproot Depths',
  },
  {
    id: 12040800,
    name: 'Astel, Naturalborn of the Void',
    category: 'boss',
    location: 'Grand Cloister',
  },
  {
    id: 12050800,
    name: 'Mohg, Lord of Blood',
    category: 'boss',
    location: 'Mohgwyn Palace',
  },
  {
    id: 12080800,
    name: 'Ancestor Spirit',
    category: 'boss',
    location: 'Siofra River',
  },
  {
    id: 12090800,
    name: 'Regal Ancestor Spirit',
    category: 'boss',
    location: 'Nokron, Eternal City',
  },
  {
    id: 13000800,
    name: 'Beast Clergyman / Maliketh, the Black Blade',
    category: 'boss',
    location: 'Crumbling Farum Azula',
  },
  {
    id: 13000830,
    name: 'Dragonlord Placidusax',
    category: 'boss',
    location: 'Crumbling Farum Azula',
  },
  {
    id: 13000850,
    name: 'Godskin Duo',
    category: 'boss',
    location: 'Crumbling Farum Azula',
  },
  {
    id: 14000800,
    name: 'Rennala, Queen of the Full Moon',
    category: 'boss',
    location: 'Academy of Raya Lucaria',
  },
  {
    id: 14000850,
    name: 'Red Wolf of Radagon',
    category: 'boss',
    location: 'Academy of Raya Lucaria',
  },
  {
    id: 15000800,
    name: 'Malenia, Blade of Miquella',
    category: 'boss',
    location: 'Elphael, Brace of the Haligtree',
  },
  {
    id: 15000850,
    name: 'Loretta, Knight of the Haligtree',
    category: 'boss',
    location: "Miquella's Haligtree",
  },
  {
    id: 16000800,
    name: 'Rykard, Lord of Blasphemy',
    category: 'boss',
    location: 'Volcano Manor',
  },
  {
    id: 16000850,
    name: 'Godskin Noble',
    category: 'boss',
    location: 'Volcano Manor',
  },
  {
    id: 16000860,
    name: 'Abductor Virgins',
    category: 'boss',
    location: 'Volcano Manor',
  },
  {
    id: 18000800,
    name: 'Ulcerated Tree Spirit',
    category: 'boss',
    location: "Fringefolk Hero's Grave",
  },
  {
    id: 18000850,
    name: 'Soldier of Godrick',
    category: 'boss',
    location: 'Cave of Knowledge',
  },
  {
    id: 19000800,
    name: 'Elden Beast',
    category: 'boss',
    location: 'Leyndell, Ashen Capital',
  },
  {
    id: 20000800,
    name: 'Divine Beast Dancing Lion',
    category: 'boss',
    location: 'Belurat, Tower Settlement ',
  },
  {
    id: 20010800,
    name: 'Promised Consort Radahn',
    category: 'boss',
    location: 'Enir-Ilim',
  },
  {
    id: 21000850,
    name: 'Golden Hippopotamus',
    category: 'boss',
    location: 'Shadow Keep',
  },
  {
    id: 21010800,
    name: 'Messmer the Impaler',
    category: 'boss',
    location: 'Shadow Keep',
  },
  {
    id: 22000800,
    name: 'Putrescent Knight',
    category: 'boss',
    location: 'Stone Coffin Fissure',
  },
  {
    id: 25000800,
    name: 'Metyr, Mother of Fingers',
    category: 'boss',
    location: 'Finger Ruins of Miyr',
  },
  {
    id: 28000800,
    name: 'Midra, Lord of Frenzied Flame',
    category: 'boss',
    location: "Midra's Manse",
  },
  {
    id: 30000800,
    name: 'Cemetery Shade',
    category: 'boss',
    location: 'Tombsward Catacombs',
  },
  {
    id: 30010800,
    name: 'Erdtree Burial Watchdog',
    category: 'boss',
    location: "Impaler's Catacombs",
  },
  {
    id: 30020800,
    name: 'Erdtree Burial Watchdog',
    category: 'boss',
    location: 'Stormfoot Catacombs',
  },
  {
    id: 30030800,
    name: 'Spirit-Caller Snail',
    category: 'boss',
    location: "Road's End Catacombs",
  },
  {
    id: 30040800,
    name: 'Grave Warden Duelist',
    category: 'boss',
    location: 'Murkwater Catacombs',
  },
  {
    id: 30050800,
    name: 'Cemetery Shade',
    category: 'boss',
    location: 'Black Knife Catacombs',
  },
  {
    id: 30050850,
    name: 'Black Knife Assassin',
    category: 'boss',
    location: 'Black Knife Catacombs',
  },
  {
    id: 30060800,
    name: 'Erdtree Burial Watchdog',
    category: 'boss',
    location: 'Cliffbottom Catacombs',
  },
  {
    id: 30070800,
    name: 'Erdtree Burial Watchdog',
    category: 'boss',
    location: 'Wyndham Catacombs',
  },
  {
    id: 30080800,
    name: 'Ancient Hero of Zamor',
    category: 'boss',
    location: "Sainted Hero's Grave",
  },
  {
    id: 30090800,
    name: 'Red Wolf of the Champion',
    category: 'boss',
    location: "Gelmir Hero's Grave",
  },
  {
    id: 30100800,
    name: 'Crucible Knight & Crucible Knight Ordovis',
    category: 'boss',
    location: "Azuria Hero's Grave",
  },
  {
    id: 30110800,
    name: 'Black Knife Assassin',
    category: 'boss',
    location: 'Deathtouched Catacombs',
  },
  {
    id: 30120800,
    name: 'Perfumer Tricia & Misbegotten Warrior',
    category: 'boss',
    location: 'Unsightly Catacombs',
  },
  {
    id: 30130800,
    name: 'Grave Warden Duelist',
    category: 'boss',
    location: 'Azuria Side Tomb',
  },
  {
    id: 30140800,
    name: 'Erdtree Burial Watchdog Duo',
    category: 'boss',
    location: 'Minor Erdtree Catacombs',
  },
  {
    id: 30150800,
    name: 'Cemetery Shade',
    category: 'boss',
    location: 'Caelid Catacombs',
  },
  {
    id: 30160800,
    name: 'Putrid Tree Spirit',
    category: 'boss',
    location: 'War-Dead Catacombs',
  },
  {
    id: 30170800,
    name: 'Ancient Hero of Zamor',
    category: 'boss',
    location: "Giant-Conquering Hero's Grave",
  },
  {
    id: 30180800,
    name: 'Ulcerated Tree Spirit',
    category: 'boss',
    location: 'Mountaintop Catacombs',
  },
  {
    id: 30190800,
    name: 'Putrid Grave Warden Duelist',
    category: 'boss',
    location: 'Consecrated Snowfield Catacombs',
  },
  {
    id: 30200800,
    name: 'Stray Mimic Tear',
    category: 'boss',
    location: 'Hidden Path to the Haligtree',
  },
  {
    id: 31000800,
    name: 'Patches',
    category: 'boss',
    location: 'Murkwater Cave',
  },
  {
    id: 31010800,
    name: 'Runebear',
    category: 'boss',
    location: 'Earthbore Cave',
  },
  {
    id: 31020800,
    name: 'Miranda the Blighted Bloom',
    category: 'boss',
    location: 'Tombsward Cave',
  },
  {
    id: 31030800,
    name: 'Beastman of Farum Azula',
    category: 'boss',
    location: 'Groveside Cave',
  },
  {
    id: 31040800,
    name: 'Cleanrot Knight',
    category: 'boss',
    location: 'Stillwater Cave',
  },
  {
    id: 31050800,
    name: 'Bloodhound Knight',
    category: 'boss',
    location: 'Lakeside Crystal Cave',
  },
  {
    id: 31060800,
    name: 'Crystalian Duo',
    category: 'boss',
    location: 'Academy Crystal Cave',
  },
  {
    id: 31070800,
    name: 'Kindred of Rot Duo',
    category: 'boss',
    location: 'Seethewater Cave',
  },
  {
    id: 31090800,
    name: 'Demi-Human Queen Margot',
    category: 'boss',
    location: 'Volcano Cave',
  },
  {
    id: 31100800,
    name: 'Beastman of Farum Azula Duo',
    category: 'boss',
    location: 'Dragonbarrow Cave',
  },
  {
    id: 31110800,
    name: 'Putrid Crystalian Trio',
    category: 'boss',
    location: 'Sellia Hideaway',
  },
  {
    id: 31120800,
    name: 'Misbegotten Crusader',
    category: 'boss',
    location: 'Cave of the Forlorn',
  },
  {
    id: 31150800,
    name: 'Demi-Human Chiefs',
    category: 'boss',
    location: 'Coastal Cave Dungeon',
  },
  {
    id: 31170800,
    name: 'Guardian Golem',
    category: 'boss',
    location: 'Highroad Cave',
  },
  {
    id: 31180800,
    name: 'Omenkiller & Miranda the Blighted Bloom',
    category: 'boss',
    location: "Perfumer's Grotto",
  },
  {
    id: 31190800,
    name: "Black Knife Assassin (Sage's Cave)",
    category: 'boss',
    location: "Sage's Cave",
  },
  {
    id: 31190850,
    name: 'Necromancer Garris',
    category: 'boss',
    location: "Sage's Cave",
  },
  {
    id: 31200800,
    name: 'Cleanrot Knight',
    category: 'boss',
    location: 'Abandoned Cave',
  },
  {
    id: 31210800,
    name: 'Frenzied Duelist',
    category: 'boss',
    location: 'Gaol Cave',
  },
  {
    id: 31220800,
    name: 'Spirit-Caller Snail',
    category: 'boss',
    location: 'Spiritcaller Cave',
  },
  {
    id: 32000800,
    name: 'Scaly Misbegotten',
    category: 'boss',
    location: 'Morne Tunnel',
  },
  {
    id: 32010800,
    name: 'Stonedigger Troll',
    category: 'boss',
    location: 'Limgrave Tunnels',
  },
  {
    id: 32020800,
    name: 'Crystalian',
    category: 'boss',
    location: 'Raya Lucaria Crystal Tunnel',
  },
  {
    id: 32040800,
    name: 'Stonedigger Troll',
    category: 'boss',
    location: 'Old Altus Tunnel',
  },
  {
    id: 32050800,
    name: 'Crystalian Duo',
    category: 'boss',
    location: 'Altus Tunnel',
  },
  {
    id: 32070800,
    name: 'Magma Wyrm',
    category: 'boss',
    location: 'Gael Tunnel',
  },
  {
    id: 32080800,
    name: 'Fallingstar Beast',
    category: 'boss',
    location: 'Sellia Crystal Tunnel',
  },
  {
    id: 32110800,
    name: 'Astel, Stars of Darkness',
    category: 'boss',
    location: 'Yelough Anix Tunnel',
  },
  {
    id: 34120800,
    name: 'Onyx Lord',
    category: 'boss',
    location: 'Sealed Tunnel',
  },
  {
    id: 34130800,
    name: 'Godskin Apostle',
    category: 'boss',
    location: 'Divine Tower of Caelid',
  },
  {
    id: 34140850,
    name: 'Fell Twins',
    category: 'boss',
    location: 'Divine Tower Bridge',
  },
  {
    id: 35000800,
    name: 'Mohg, the Omen',
    category: 'boss',
    location: 'Subterranean Shunning-Grounds',
  },
  {
    id: 35000850,
    name: 'Esgar, Priest of Blood',
    category: 'boss',
    location: 'Leyndell Catacombs',
  },
  {
    id: 39200800,
    name: 'Magma Wyrm Makar',
    category: 'boss',
    location: 'Ruin-Strewn Precipice',
  },
  {
    id: 40000800,
    name: 'Death Knight',
    category: 'boss',
    location: 'Fog Rift Catacombs',
  },
  {
    id: 40010800,
    name: 'Death Knight',
    category: 'boss',
    location: 'Scorpion River Catacombs',
  },
  {
    id: 41000800,
    name: 'Demi-Human Swordmaster Onze',
    category: 'boss',
    location: 'Belurat Gaol',
  },
  {
    id: 41010800,
    name: 'Curseblade Labirith',
    category: 'boss',
    location: 'Bonny Gaol',
  },
  {
    id: 41020800,
    name: 'Lamenter',
    category: 'boss',
    location: "Lamenter's Gaol",
  },
  {
    id: 43000800,
    name: 'Chief Bloodfiend',
    category: 'boss',
    location: 'Rivermouth Cave',
  },
  {
    id: 43010800,
    name: 'Ancient Dragon-Man',
    category: 'boss',
    location: "Dragon's Pit",
  },
  {
    id: 1033420800,
    name: 'Alecto, Black Knife Ringleader',
    category: 'boss',
    location: "Ringleader's Evergaol",
  },
  {
    id: 1033430800,
    name: 'Erdtree Avatar (SW)',
    category: 'boss',
    location: 'Minor Erdtree (Liurnia Southwest)',
  },
  {
    id: 1033450800,
    name: 'Bols, Carian Knight',
    category: 'boss',
    location: "Cuckoo's Evergaol",
  },
  {
    id: 1034420800,
    name: 'Glintstone Dragon Adula',
    category: 'boss',
    location: 'Cathedral of Manus Celes',
  },
  {
    id: 1034450800,
    name: 'Glintstone Dragon Smarag',
    category: 'boss',
    location: 'Liurnia of the Lakes',
  },
  {
    id: 1034480800,
    name: 'Royal Revenant',
    category: 'boss',
    location: 'Kingsrealm Ruins',
  },
  {
    id: 1035420800,
    name: 'Omenkiller',
    category: 'boss',
    location: 'Village of the Albinaurics',
  },
  {
    id: 1035500800,
    name: 'Royal Knight Loretta',
    category: 'boss',
    location: 'Caria Manor',
  },
  {
    id: 1035530800,
    name: 'Magma Wyrm',
    category: 'boss',
    location: 'Mt. Gelmir',
  },
  {
    id: 1036450800,
    name: 'Death Rite Bird',
    category: 'boss',
    location: 'Academy Gate Town',
  },
  {
    id: 1036480800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Liurnia North',
  },
  {
    id: 1036500800,
    name: 'Onyx Lord',
    category: 'boss',
    location: 'Royal Grave Evergaol',
  },
  {
    id: 1036540800,
    name: 'Full-Grown Fallingstar Beast',
    category: 'boss',
    location: 'Mt. Gelmir',
  },
  {
    id: 1037420800,
    name: 'Deathbird',
    category: 'boss',
    location: 'Liurnia of the Lakes',
  },
  {
    id: 1037460800,
    name: 'Bell Bearing Hunter',
    category: 'boss',
    location: 'Church of Vows',
  },
  {
    id: 1037510800,
    name: 'Ancient Dragon Lansseax',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1037530800,
    name: 'Demi-Human Queen Maggie',
    category: 'boss',
    location: 'Hermit Village',
  },
  {
    id: 1037540810,
    name: 'Ulcerated Tree Spirit',
    category: 'boss',
    location: 'Mt. Gelmir',
  },
  {
    id: 1038410800,
    name: 'Adan, Thief of Fire',
    category: 'boss',
    location: "Malefactor's Evergaol",
  },
  {
    id: 1038480800,
    name: 'Erdtree Avatar (NE)',
    category: 'boss',
    location: 'Minor Erdtree (Liurnia Northeast)',
  },
  {
    id: 1038510800,
    name: 'Demi-Human Queen Gilika',
    category: 'boss',
    location: 'Lux Ruins',
  },
  {
    id: 1038520800,
    name: 'Tibia Mariner',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1039430800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Liurnia South',
  },
  {
    id: 1039440800,
    name: 'Tibia Mariner',
    category: 'boss',
    location: 'Liurnia of the Lakes',
  },
  {
    id: 1039500800,
    name: 'Godefroy the Grafted',
    category: 'boss',
    location: 'Golden Lineage Evergaol',
  },
  {
    id: 1039510800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1039540800,
    name: 'Elemer of the Briar',
    category: 'boss',
    location: 'Shaded Castle',
  },
  {
    id: 1040520800,
    name: "Black Knife Assassin (Sainted Hero's Grave)",
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1040530800,
    name: 'Sanguine Noble',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1041500800,
    name: 'Fallingstar Beast',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1041510800,
    name: 'Tree Sentinel Duo',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1041530800,
    name: 'Wormface',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1042330800,
    name: 'Ancient Hero of Zamor',
    category: 'boss',
    location: 'Weeping Evergaol',
  },
  {
    id: 1042360800,
    name: 'Tree Sentinel',
    category: 'boss',
    location: 'Limgrave',
  },
  {
    id: 1042370800,
    name: 'Crucible Knight',
    category: 'boss',
    location: 'Stormhill Evergaol',
  },
  {
    id: 1042380800,
    name: 'Deathbird',
    category: 'boss',
    location: 'Limgrave',
  },
  {
    id: 1042380850,
    name: 'Bell Bearing Hunter',
    category: 'boss',
    location: "Warmaster's Shack",
  },
  {
    id: 1042550800,
    name: 'Godskin Apostle',
    category: 'boss',
    location: 'Windmill Village',
  },
  {
    id: 1043300800,
    name: 'Leonine Misbegotten',
    category: 'boss',
    location: 'Castle Morne',
  },
  {
    id: 1043330800,
    name: 'Erdtree Avatar',
    category: 'boss',
    location: 'Weeping Penisula',
  },
  {
    id: 1043360800,
    name: 'Flying Dragon Agheel',
    category: 'boss',
    location: 'Dragon-Burnt Ruins',
  },
  {
    id: 1043370800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Limgrave',
  },
  {
    id: 1043530800,
    name: 'Bell Bearing Hunter',
    category: 'boss',
    location: "Hermit Merchant's Shack",
  },
  {
    id: 1044320800,
    name: 'Deathbird',
    category: 'boss',
    location: 'Weeping Penisula',
  },
  {
    id: 1044320850,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Weeping Penisula',
  },
  {
    id: 1044350800,
    name: 'Bloodhound Knight Darriwil',
    category: 'boss',
    location: 'Forlorn Hound Evergaol',
  },
  {
    id: 1044360800,
    name: 'Mad Pumpkin Head',
    category: 'boss',
    location: 'Waypoint Ruins',
  },
  {
    id: 1044530800,
    name: 'Deathbird',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1045390800,
    name: 'Tibia Mariner',
    category: 'boss',
    location: 'Summonwater Village',
  },
  {
    id: 1045520800,
    name: 'Draconic Tree Sentinel',
    category: 'boss',
    location: 'Capital Outskirts',
  },
  {
    id: 1047400800,
    name: 'Putrid Avatar',
    category: 'boss',
    location: 'Minor Erdtree (Caelid)',
  },
  {
    id: 1048370800,
    name: 'Decaying Ekzykes',
    category: 'boss',
    location: 'Caelid',
  },
  {
    id: 1048400800,
    name: 'Mad Pumpkin Head Duo',
    category: 'boss',
    location: 'Caelem Ruins',
  },
  {
    id: 1048410800,
    name: 'Bell Bearing Hunter',
    category: 'boss',
    location: "Isolated Merchant's Shack",
  },
  {
    id: 1048510800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Forbidden Lands',
  },
  {
    id: 1048570800,
    name: 'Death Rite Bird',
    category: 'boss',
    location: 'Concecrated Snowfield',
  },
  {
    id: 1049370800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Caelid',
  },
  {
    id: 1049370850,
    name: 'Death Rite Bird',
    category: 'boss',
    location: 'Caelid',
  },
  {
    id: 1049380800,
    name: "Commander O'Neil",
    category: 'boss',
    location: 'Swamp of Aeonia',
  },
  {
    id: 1049390800,
    name: 'Nox Swordstress & Nox Priest',
    category: 'boss',
    location: 'Sellia, Town of Sorcery',
  },
  {
    id: 1049390850,
    name: 'Battlemage Hugues',
    category: 'boss',
    location: 'Sellia Evergaol',
  },
  {
    id: 1049520800,
    name: 'Black Blade Kindred',
    category: 'boss',
    location: 'Forbidden Lands',
  },
  {
    id: 1050560800,
    name: 'Great Wyrm Theodorix',
    category: 'boss',
    location: 'Concecrated Snowfield',
  },
  {
    id: 1050570800,
    name: 'Death Rite Bird',
    category: 'boss',
    location: 'Mountaintops of the Giants',
  },
  {
    id: 1050570850,
    name: 'Putrid Avatar',
    category: 'boss',
    location: 'Minor Erdtree (Consecrated Snowfield)',
  },
  {
    id: 1051360800,
    name: 'Crucible Knight & Misbegotten Warrior',
    category: 'boss',
    location: 'Redmane Castle',
  },
  {
    id: 1051400800,
    name: 'Putrid Avatar',
    category: 'boss',
    location: 'Minor Erdtree (Dragonbarrow)',
  },
  {
    id: 1051430800,
    name: 'Black Blade Kindred',
    category: 'boss',
    location: 'Bestial Sanctum',
  },
  {
    id: 1051570800,
    name: 'Commander Niall',
    category: 'boss',
    location: 'Castle Sol',
  },
  {
    id: 1052410800,
    name: 'Flying Dragon Greyll',
    category: 'boss',
    location: 'Dragonbarrow',
  },
  {
    id: 1052410850,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Dragonbarrow',
  },
  {
    id: 1052560800,
    name: 'Erdtree Avatar',
    category: 'boss',
    location: 'Minor Erdtree (Mountaintops East)',
  },
  {
    id: 1053560800,
    name: 'Roundtable Knight Vyke',
    category: 'boss',
    location: "Lord Contender's Evergaol",
  },
  {
    id: 1248550800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Consecrated Snowfield',
  },
  {
    id: 1252380800,
    name: 'Starscourge Radahn',
    category: 'boss',
    location: 'Wailing Dunes',
  },
  {
    id: 1252520800,
    name: 'Fire Giant',
    category: 'boss',
    location: 'Flame Peak',
  },
  {
    id: 1254560800,
    name: 'Borealis the Freezing Fog',
    category: 'boss',
    location: 'Mountaintops of the Giants',
  },
  {
    id: 2044450800,
    name: 'Romina, Saint of the Bud',
    category: 'boss',
    location: 'Church of the Bud',
  },
  {
    id: 2044470800,
    name: 'Rugalea the Great Red Bear',
    category: 'boss',
    location: 'Rauh Base',
  },
  {
    id: 2045440800,
    name: 'Ghostflame Dragon',
    category: 'boss',
    location: 'Gravesite Plain',
  },
  {
    id: 2046380800,
    name: 'Dancer of Ranah',
    category: 'boss',
    location: 'Southern Nameless Mausoleum',
  },
  {
    id: 2046400800,
    name: 'Demi-Human Queen Marigga',
    category: 'boss',
    location: 'Cerulean Coast',
  },
  {
    id: 2046410800,
    name: 'Knight of the Solitary Gaol',
    category: 'boss',
    location: 'Western Nameless Mausoleum',
  },
  {
    id: 2046450800,
    name: 'Red Bear',
    category: 'boss',
    location: 'Northern Nameless Mausoleum',
  },
  {
    id: 2046460800,
    name: 'Divine Beast Dancing Lion',
    category: 'boss',
    location: 'Ancient Ruins of Rauh',
  },
  {
    id: 2047390800,
    name: 'Death Rite Bird',
    category: 'boss',
    location: "Charo's Hidden Grave",
  },
  {
    id: 2047450800,
    name: 'Black Knight Garrew',
    category: 'boss',
    location: 'Fog Rift Fort',
  },
  {
    id: 2048380850,
    name: 'Ghostflame Dragon',
    category: 'boss',
    location: 'Cerulean Coast',
  },
  {
    id: 2048440800,
    name: 'Rellana, Twin Moon Knight',
    category: 'boss',
    location: 'Castle Ensis',
  },
  {
    id: 2049410800,
    name: 'Jagged Peak Drake',
    category: 'boss',
    location: 'Jagged Peak Foothills',
  },
  {
    id: 2049430800,
    name: 'Ghostflame Dragon',
    category: 'boss',
    location: 'Moorth Highway',
  },
  {
    id: 2049430850,
    name: 'Black Knight Edredd',
    category: 'boss',
    location: 'Fort of Reprimand',
  },
  {
    id: 2049440800,
    name: 'Dryleaf Dane',
    category: 'boss',
    location: 'Moorth Ruins',
  },
  {
    id: 2049450800,
    name: 'Ralva the Great Red Bear',
    category: 'boss',
    location: 'Scadu Altus',
  },
  {
    id: 2049480800,
    name: 'Commander Gaius',
    category: 'boss',
    location: 'Scaduview',
  },
  {
    id: 2050470800,
    name: 'Tree Sentinel (Ambush)',
    category: 'boss',
    location: 'Hinterland',
  },
  {
    id: 2050480800,
    name: 'Scadutree Avatar',
    category: 'boss',
    location: 'Scadutree Base',
  },
  {
    id: 2050480860,
    name: 'Tree Sentinel (Exposed)',
    category: 'boss',
    location: 'Hinterland',
  },
  {
    id: 2051440800,
    name: 'Rakshasa',
    category: 'boss',
    location: 'Eastern Nameless Mausoleum',
  },
  {
    id: 2051450800,
    name: 'Count Ymir, Mother of Fingers',
    category: 'boss',
    location: 'Cathedral of Manus Metyr',
  },
  {
    id: 2052400800,
    name: 'Jagged Peak Drake Duo',
    category: 'boss',
    location: 'Jagged Peak',
  },
  {
    id: 2052430800,
    name: 'Jori, Elder Inquisitor',
    category: 'boss',
    location: 'Darklight Catacombs',
  },
  {
    id: 2052480800,
    name: 'Fallingstar Beast',
    category: 'boss',
    location: 'Finger Ruins of Dheo',
  },
  {
    id: 2054390800,
    name: 'Bayle, the Dread',
    category: 'boss',
    location: 'Jagged Peak',
  },
  {
    id: 2054390850,
    name: 'Ancient Dragon Senessax',
    category: 'boss',
    location: 'Jagged Peak',
  },
]
