import { type EventFlag } from './types'

export const eventFlags: EventFlag[] = [
  {
    id: 20,
    name: 'Playthrough Complete: Age of Fracture',
    category: 'ending',
  },
  {
    id: 21,
    name: 'Playthrough Complete: Age of Stars',
    category: 'ending',
  },
  {
    id: 22,
    name: 'Playthrough Complete: Lord of the Frenzied Flame',
    category: 'ending',
  },
  {
    id: 30,
    name: 'Trigger New Game Plus',
    category: 'ng',
  },
  {
    id: 50,
    name: 'Playthrough Lap: 0',
    category: 'ng',
  },
  {
    id: 51,
    name: 'Playthrough Lap: 1',
    category: 'ng',
  },
  {
    id: 52,
    name: 'Playthrough Lap: 2',
    category: 'ng',
  },
  {
    id: 53,
    name: 'Playthrough Lap: 3',
    category: 'ng',
  },
  {
    id: 54,
    name: 'Playthrough Lap: 4',
    category: 'ng',
  },
  {
    id: 55,
    name: 'Playthrough Lap: 5',
    category: 'ng',
  },
  {
    id: 56,
    name: 'Playthrough Lap: 6',
    category: 'ng',
  },
  {
    id: 57,
    name: 'Playthrough Lap: 7',
    category: 'ng',
  },
  {
    id: 58,
    name: 'Playthrough Lap: 8',
    category: 'ng',
  },
  {
    id: 70,
    name: 'Apply DLC Game Clear SpEffect (Occurs if Radahn, Consort of Miquella is beated and NG+ is entered)',
    category: 'dlcClear',
  },
  {
    id: 100,
    name: 'Story: Start',
    category: 'story',
  },
  {
    id: 101,
    name: 'Story: Reached Tutorial',
    category: 'story',
  },
  {
    id: 102,
    name: 'Story: Reached Limgrave',
    category: 'story',
  },
  {
    id: 104,
    name: 'Story: Reached Roundtable Hold',
    category: 'story',
  },
  {
    id: 105,
    name: 'Story: Roundtable Hold Introduction',
    category: 'story',
  },
  {
    id: 108,
    name: 'Story: Received the Frenzied Flame',
    category: 'story',
  },
  {
    id: 109,
    name: 'Story: Received the Frenzied Flame (back)',
    category: 'story',
  },
  {
    id: 110,
    name: 'Story: Reached Forge of the Giants',
    category: 'story',
  },
  {
    id: 111,
    name: 'Story: Forge of the Giants - Melina A',
    category: 'story',
  },
  {
    id: 112,
    name: 'Story: Forge of the Giants - Melina B',
    category: 'story',
  },
  {
    id: 114,
    name: 'Story: Ranni',
    category: 'story',
  },
  {
    id: 116,
    name: 'Story: Frenzied Flame Nullified',
    category: 'story',
  },
  {
    id: 118,
    name: 'Story: Erdtree on Fire',
    category: 'story',
  },
  {
    id: 120,
    name: 'Story: Watched Ending',
    category: 'story',
  },
  {
    id: 130,
    name: 'Arrival: Stormveil Castle',
    category: 'arrival',
  },
  {
    id: 131,
    name: 'Arrival: Morne Castle',
    category: 'arrival',
  },
  {
    id: 132,
    name: 'Arrival: Academy of Raya Lucaria',
    category: 'arrival',
  },
  {
    id: 133,
    name: 'Arrival: Ruin-Strewn Precipice',
    category: 'arrival',
  },
  {
    id: 134,
    name: 'Arrival: Volcano Manor',
    category: 'arrival',
  },
  {
    id: 135,
    name: 'Arrival: Volcano Manor (Inner)',
    category: 'arrival',
  },
  {
    id: 136,
    name: 'Arrival: Leyndell, Royal Capital',
    category: 'arrival',
  },
  {
    id: 137,
    name: 'Arrival: Subterranean Shunning-Grounds',
    category: 'arrival',
  },
  {
    id: 138,
    name: "Arrival: Miquella's Haligtree - Canopy",
    category: 'arrival',
  },
  {
    id: 139,
    name: "Arrival: Miquella's Haligtree - Trunk",
    category: 'arrival',
  },
  {
    id: 140,
    name: 'Arrival: Downhill Ruins',
    category: 'arrival',
  },
  {
    id: 180,
    name: 'Great Rune Count: 0',
    category: 'greatRuneCount',
  },
  {
    id: 181,
    name: 'Great Rune Count: 1',
    category: 'greatRuneCount',
  },
  {
    id: 182,
    name: 'Great Rune Count: 2',
    category: 'greatRuneCount',
  },
  {
    id: 183,
    name: 'Great Rune Count: 3',
    category: 'greatRuneCount',
  },
  {
    id: 184,
    name: 'Great Rune Count: 4',
    category: 'greatRuneCount',
  },
  {
    id: 185,
    name: 'Great Rune Count: 5',
    category: 'greatRuneCount',
  },
  {
    id: 186,
    name: 'Great Rune Count: 6',
    category: 'greatRuneCount',
  },
  {
    id: 187,
    name: 'Great Rune Count: 7',
    category: 'greatRuneCount',
  },
  {
    id: 191,
    name: "Acquired Godrick's Great Rune",
    category: 'greatRune',
  },
  {
    id: 192,
    name: "Acquired Radahn's Great Rune",
    category: 'greatRune',
  },
  {
    id: 193,
    name: "Acquired Morgott's Great Rune",
    category: 'greatRune',
  },
  {
    id: 194,
    name: "Acquired Rykard's Great Rune",
    category: 'greatRune',
  },
  {
    id: 195,
    name: "Acquired Mohg's Great Rune",
    category: 'greatRune',
  },
  {
    id: 196,
    name: "Acquired Malenia's Great Rune",
    category: 'greatRune',
  },
  {
    id: 197,
    name: 'Acquired Great Rune of the Unborn',
    category: 'greatRune',
  },
  {
    id: 200,
    name: 'Is Host',
    category: 'other',
  },
  {
    id: 201,
    name: 'Is Guest',
    category: 'other',
  },
  {
    id: 210,
    name: 'Host in Legacy Dungeon',
    category: 'other',
  },
  {
    id: 211,
    name: 'Guest in Legacy Dungeon',
    category: 'other',
  },
  {
    id: 220,
    name: 'Host in Legacy Dungeon',
    category: 'other',
  },
  {
    id: 221,
    name: 'Guest in Legacy Dungeon',
    category: 'other',
  },
  {
    id: 300,
    name: 'World Event: Erdtree Burnt',
    category: 'worldEvent',
  },
  {
    id: 301,
    name: 'World Event: Erdtree Burnt (Flaming Sparks)',
    category: 'worldEvent',
  },
  {
    id: 302,
    name: 'World Event: Erdtree Burnt (Small Flames)',
    category: 'worldEvent',
  },
  {
    id: 310,
    name: 'World Event: Green Meteorite',
    category: 'worldEvent',
  },
  {
    id: 311,
    name: 'World Event: Snowfield Meteorite',
    category: 'worldEvent',
  },
  {
    id: 312,
    name: 'World Event: Plain Meteorite',
    category: 'worldEvent',
  },
  {
    id: 320,
    name: 'World Event: Carian Study Hall Reversal',
    category: 'worldEvent',
  },
  {
    id: 370,
    name: 'World Event: Carian Study Hall Reversal',
    category: 'worldEvent',
  },
  {
    id: 530,
    name: 'Time: Morning',
    category: 'time',
  },
  {
    id: 531,
    name: 'Time: Noon',
    category: 'time',
  },
  {
    id: 532,
    name: 'Time: Night',
    category: 'time',
  },
  {
    id: 550,
    name: 'Weather: Fine',
    category: 'weather',
  },
  {
    id: 551,
    name: 'Weather: Sunny',
    category: 'weather',
  },
  {
    id: 552,
    name: 'Weather: Cloudy',
    category: 'weather',
  },
  {
    id: 553,
    name: 'Weather: Lightly Cloudy',
    category: 'weather',
  },
  {
    id: 554,
    name: 'Weather: Rain',
    category: 'weather',
  },
  {
    id: 555,
    name: 'Weather: Heavy Rain',
    category: 'weather',
  },
  {
    id: 556,
    name: 'Weather: Storm',
    category: 'weather',
  },
  {
    id: 557,
    name: 'Weather: Storm',
    category: 'weather',
  },
  {
    id: 558,
    name: 'Weather: Snow',
    category: 'weather',
  },
  {
    id: 559,
    name: 'Weather: Heavy Snow',
    category: 'weather',
  },
  {
    id: 560,
    name: 'Weather: Fog',
    category: 'weather',
  },
  {
    id: 561,
    name: 'Weather: Thick Fog',
    category: 'weather',
  },
  {
    id: 562,
    name: 'Weather: Thick Fog and Rain',
    category: 'weather',
  },
  {
    id: 563,
    name: 'Weather: Sandstorm',
    category: 'weather',
  },
  {
    id: 570,
    name: 'Weather Group: Fine',
    category: 'weatherGroup',
  },
  {
    id: 571,
    name: 'Weather Group: Cloudy',
    category: 'weatherGroup',
  },
  {
    id: 572,
    name: 'Weather Group: Rain',
    category: 'weatherGroup',
  },
  {
    id: 573,
    name: 'Weather Group: Snow',
    category: 'weatherGroup',
  },
  {
    id: 574,
    name: 'Weather Group: Fog',
    category: 'weatherGroup',
  },
  {
    id: 575,
    name: 'Weather Group: Other',
    category: 'weatherGroup',
  },
  {
    id: 1000,
    name: 'default',
    category: 'other',
  },
  {
    id: 6000,
    name: 'Always OFF',
    category: 'other',
  },
  {
    id: 6001,
    name: 'Always ON',
    category: 'other',
  },
  {
    id: 9100,
    name: 'Defeated Godrick the Grafted',
    category: 'defeated',
  },
  {
    id: 9101,
    name: 'Defeated Margit, the Fell Omen',
    category: 'defeated',
  },
  {
    id: 9103,
    name: 'Defeated Grafted Scion',
    category: 'defeated',
  },
  {
    id: 9104,
    name: 'Defeated Morgott, the Omen King',
    category: 'defeated',
  },
  {
    id: 9105,
    name: 'Defeated Godfrey, First Elden Lord',
    category: 'defeated',
  },
  {
    id: 9106,
    name: 'Defeated Sir Gideon Ofnir, the All-Knowing',
    category: 'defeated',
  },
  {
    id: 9107,
    name: 'Defeated Hoarah Loux',
    category: 'defeated',
  },
  {
    id: 9108,
    name: 'Defeated Astel, Naturalborn of the Void',
    category: 'defeated',
  },
  {
    id: 9109,
    name: 'Defeated Dragonkin Soldier of Nokstella',
    category: 'defeated',
  },
  {
    id: 9111,
    name: 'Defeated Lichdragon Fortissax',
    category: 'defeated',
  },
  {
    id: 9112,
    name: 'Defeated Mohg, Lord of Blood',
    category: 'defeated',
  },
  {
    id: 9115,
    name: 'Defeated Dragonlord Placidusax',
    category: 'defeated',
  },
  {
    id: 9116,
    name: 'Defeated Maliketh, the Black Blade',
    category: 'defeated',
  },
  {
    id: 9118,
    name: 'Defeated Rennala, Queen of the Full Moon',
    category: 'defeated',
  },
  {
    id: 9119,
    name: 'Defeated Royal Knight Loretta',
    category: 'defeated',
  },
  {
    id: 9120,
    name: 'Defeated Malenia, Blade of Miquella',
    category: 'defeated',
  },
  {
    id: 9122,
    name: 'Defeated Rykard, Lord of Blasphemy',
    category: 'defeated',
  },
  {
    id: 9123,
    name: 'Defeated the Elden Beast',
    category: 'defeated',
  },
  {
    id: 9130,
    name: 'Defeated Starscourge Radahn',
    category: 'defeated',
  },
  {
    id: 9131,
    name: 'Defeated Fire Giant',
    category: 'defeated',
  },
  {
    id: 9133,
    name: 'Defeated Regal Ancestor Spirit',
    category: 'defeated',
  },
  {
    id: 9134,
    name: 'Defeated Dragonkin Soldier - Lake of Rot',
    category: 'defeated',
  },
  {
    id: 9135,
    name: "Defeated Fia's Champion",
    category: 'defeated',
  },
  {
    id: 9140,
    name: 'Defeated Divine Beast Dancing Lion',
    category: 'defeated',
  },
  {
    id: 9143,
    name: 'Defeated Radahn, Consort of Miquella',
    category: 'defeated',
  },
  {
    id: 9146,
    name: 'Defeated Messmer the Impaler',
    category: 'defeated',
  },
  {
    id: 9148,
    name: 'Defeated Putrescent Knight',
    category: 'defeated',
  },
  {
    id: 9155,
    name: 'Defeated Metyr, Mother of Fingers',
    category: 'defeated',
  },
  {
    id: 9156,
    name: 'Defeated Midra, Lord of Frenzied Flame',
    category: 'defeated',
  },
  {
    id: 9160,
    name: 'Defeated Romina, Saint of the Bud',
    category: 'defeated',
  },
  {
    id: 9162,
    name: 'Defeated Scadutree Avatar',
    category: 'defeated',
  },
  {
    id: 9164,
    name: 'Defeated Commander Gaius',
    category: 'defeated',
  },
  {
    id: 9182,
    name: 'Defeated Elemer of the Briar',
    category: 'defeated',
  },
  {
    id: 9184,
    name: 'Defeated Commander Niall',
    category: 'defeated',
  },
  {
    id: 9190,
    name: 'Defeated Rellana, Twin Moon Knight',
    category: 'defeated',
  },
  {
    id: 9500,
    name: 'Obtained Mending Rune of Perfect Order',
    category: 'mendingRune',
  },
  {
    id: 9502,
    name: 'Obtained Mending Rune of the Death-Prince',
    category: 'mendingRune',
  },
  {
    id: 9504,
    name: 'Obtained Mending Rune of the Fell Curse',
    category: 'mendingRune',
  },
  {
    id: 60000,
    name: 'Obtained Flask of Crimson/Cerulean Tears',
    category: 'keyItems',
  },
  {
    id: 60010,
    name: 'Obtained Flask of Cerulean Tears',
    category: 'keyItems',
  },
  {
    id: 60020,
    name: 'Obtained Flask of Wondrous Physick',
    category: 'keyItems',
  },
  {
    id: 60100,
    name: 'Obtained Spectral Steed Whisle',
    category: 'keyItems',
  },
  {
    id: 60110,
    name: 'Obtained Spirit Calling Bell',
    category: 'keyItems',
  },
  {
    id: 60120,
    name: 'Obtained Crafting Kit',
    category: 'keyItems',
  },
  {
    id: 60130,
    name: 'Obtained Whetstone Knife',
    category: 'keyItems',
  },
  {
    id: 60140,
    name: 'Obtained Tailoring Tools',
    category: 'keyItems',
  },
  {
    id: 60150,
    name: 'Obtained Golden Tailoring Tools',
    category: 'keyItems',
  },
  {
    id: 60200,
    name: 'Can Host Multiplayer',
    category: 'multiplayer',
  },
  {
    id: 60210,
    name: "Obtained Tarnished's Wizened Finger",
    category: 'multiplayer',
  },
  {
    id: 60220,
    name: "Obtained Tarnished's Furled Finger",
    category: 'multiplayer',
  },
  {
    id: 60230,
    name: 'Obtained Small Golden Effigy',
    category: 'multiplayer',
  },
  {
    id: 60240,
    name: "Obtained Duelist's Furled Finger",
    category: 'multiplayer',
  },
  {
    id: 60250,
    name: 'Obtained Small Red Effigy',
    category: 'multiplayer',
  },
  {
    id: 60260,
    name: 'Obtained Recusant Finger',
    category: 'multiplayer',
  },
  {
    id: 60270,
    name: 'Obtained Bloody Finger',
    category: 'multiplayer',
  },
  {
    id: 60280,
    name: 'Obtained White Cipher Ring',
    category: 'multiplayer',
  },
  {
    id: 60290,
    name: 'Obtained Blue Cipher Ring',
    category: 'multiplayer',
  },
  {
    id: 60300,
    name: "Obtained Taunter's Tongue",
    category: 'multiplayer',
  },
  {
    id: 60310,
    name: 'Obtained Finger Severer',
    category: 'multiplayer',
  },
  {
    id: 60400,
    name: 'Obtained Memory Stone 0',
    category: 'memoryStone',
  },
  {
    id: 60410,
    name: 'Obtained Memory Stone 1',
    category: 'memoryStone',
  },
  {
    id: 60420,
    name: 'Obtained Memory Stone 2',
    category: 'memoryStone',
  },
  {
    id: 60430,
    name: 'Obtained Memory Stone 3',
    category: 'memoryStone',
  },
  {
    id: 60440,
    name: 'Obtained Memory Stone 4',
    category: 'memoryStone',
  },
  {
    id: 60450,
    name: 'Obtained Memory Stone 5',
    category: 'memoryStone',
  },
  {
    id: 60460,
    name: 'Obtained Memory Stone 6',
    category: 'memoryStone',
  },
  {
    id: 60470,
    name: 'Obtained Memory Stone 7',
    category: 'memoryStone',
  },
  {
    id: 60500,
    name: 'Obtained Talisman Pouch 0',
    category: 'talismanPouch',
  },
  {
    id: 60510,
    name: 'Obtained Talisman Pouch 1',
    category: 'talismanPouch',
  },
  {
    id: 60520,
    name: 'Obtained Talisman Pouch 2',
    category: 'talismanPouch',
  },
  {
    id: 62000,
    name: 'Allow Map Display',
    category: 'other',
  },
  {
    id: 62001,
    name: 'Allow Underground Map Display',
    category: 'other',
  },
  {
    id: 62004,
    name: 'Allow Starfall Crater Display',
    category: 'other',
  },
  {
    id: 62010,
    name: 'Reveal Map: Limgrave, West',
    category: 'revealMap',
  },
  {
    id: 62011,
    name: 'Reveal Map: Weeping Peninsula',
    category: 'revealMap',
  },
  {
    id: 62012,
    name: 'Reveal Map: Limgrave, East',
    category: 'revealMap',
  },
  {
    id: 62020,
    name: 'Reveal Map: Liurnia, East',
    category: 'revealMap',
  },
  {
    id: 62021,
    name: 'Reveal Map: Liurnia, North',
    category: 'revealMap',
  },
  {
    id: 62022,
    name: 'Reveal Map: Liurnia, West',
    category: 'revealMap',
  },
  {
    id: 62030,
    name: 'Reveal Map: Altus Plateau',
    category: 'revealMap',
  },
  {
    id: 62031,
    name: 'Reveal Map: Leyndell, Royal Capital',
    category: 'revealMap',
  },
  {
    id: 62032,
    name: 'Reveal Map: Mt. Gelmir',
    category: 'revealMap',
  },
  {
    id: 62040,
    name: 'Reveal Map: Caelid',
    category: 'revealMap',
  },
  {
    id: 62041,
    name: 'Reveal Map: Dragonbarrow',
    category: 'revealMap',
  },
  {
    id: 62050,
    name: 'Reveal Map: Mountaintops of the Giants, West',
    category: 'revealMap',
  },
  {
    id: 62051,
    name: 'Reveal Map: Mountaintops of the Giants, East',
    category: 'revealMap',
  },
  {
    id: 62052,
    name: 'Reveal Map: Consecrated Snowfield',
    category: 'revealMap',
  },
  {
    id: 62060,
    name: 'Reveal Map: Ainsel River',
    category: 'revealMap',
  },
  {
    id: 62061,
    name: 'Reveal Map: Lake of Rot',
    category: 'revealMap',
  },
  {
    id: 62062,
    name: 'Reveal Map: Mohgwyn Palace',
    category: 'revealMap',
  },
  {
    id: 62063,
    name: 'Reveal Map: Siofra River',
    category: 'revealMap',
  },
  {
    id: 62064,
    name: 'Reveal Map: Map: Deeproot Depths',
    category: 'revealMap',
  },
  {
    id: 62080,
    name: 'Reveal Map: Gravesite Plain',
    category: 'revealMap',
  },
  {
    id: 62081,
    name: 'Reveal Map: Scadu Altus',
    category: 'revealMap',
  },
  {
    id: 62082,
    name: 'Reveal Map: Southern Shore',
    category: 'revealMap',
  },
  {
    id: 62083,
    name: 'Reveal Map: Rauh Ruins',
    category: 'revealMap',
  },
  {
    id: 62084,
    name: 'Reveal Map: Abyss',
    category: 'revealMap',
  },
  {
    id: 63010,
    name: 'Acquired Map: Limgrave, West',
    category: 'acquiredMap',
  },
  {
    id: 63011,
    name: 'Acquired Map: Weeping Peninsula',
    category: 'acquiredMap',
  },
  {
    id: 63012,
    name: 'Acquired Map: Limgrave, East',
    category: 'acquiredMap',
  },
  {
    id: 63020,
    name: 'Acquired Map: Liurnia, East',
    category: 'acquiredMap',
  },
  {
    id: 63021,
    name: 'Acquired Map: Liurnia, North',
    category: 'acquiredMap',
  },
  {
    id: 63022,
    name: 'Acquired Map: Liurnia, West',
    category: 'acquiredMap',
  },
  {
    id: 63030,
    name: 'Acquired Map: Altus Plateau',
    category: 'acquiredMap',
  },
  {
    id: 63031,
    name: 'Acquired Map: Leyndell, Royal Capital',
    category: 'acquiredMap',
  },
  {
    id: 63032,
    name: 'Acquired Map: Mt. Gelmir',
    category: 'acquiredMap',
  },
  {
    id: 63040,
    name: 'Acquired Map: Caelid',
    category: 'acquiredMap',
  },
  {
    id: 63041,
    name: 'Acquired Map: Dragonbarrow',
    category: 'acquiredMap',
  },
  {
    id: 63050,
    name: 'Acquired Map: Mountaintops of the Giants, West',
    category: 'acquiredMap',
  },
  {
    id: 63051,
    name: 'Acquired Map: Mountaintops of the Giants, East',
    category: 'acquiredMap',
  },
  {
    id: 63052,
    name: 'Acquired Map: Consecrated Snowfield',
    category: 'acquiredMap',
  },
  {
    id: 63060,
    name: 'Acquired Map: Ainsel River',
    category: 'acquiredMap',
  },
  {
    id: 63061,
    name: 'Acquired Map: Lake of Rot',
    category: 'acquiredMap',
  },
  {
    id: 63062,
    name: 'Acquired Map: Mohgwyn Palace',
    category: 'acquiredMap',
  },
  {
    id: 63063,
    name: 'Acquired Map: Siofra River',
    category: 'acquiredMap',
  },
  {
    id: 63064,
    name: 'Acquired Map: Deeproot Depths',
    category: 'acquiredMap',
  },
  {
    id: 63080,
    name: 'Acquired Map: Gravesite Plain',
    category: 'acquiredMap',
  },
  {
    id: 63081,
    name: 'Acquired Map: Scadu Altus',
    category: 'acquiredMap',
  },
  {
    id: 63082,
    name: 'Acquired Map: Southern Shore',
    category: 'acquiredMap',
  },
  {
    id: 63083,
    name: 'Acquired Map: Rauh Ruins',
    category: 'acquiredMap',
  },
  {
    id: 63084,
    name: 'Acquired Map: Abyss',
    category: 'acquiredMap',
  },
  {
    id: 65000,
    name: 'Obtained Crimsonspill Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65010,
    name: 'Obtained Greenspill Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65020,
    name: 'Obtained Crimson Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65030,
    name: 'Obtained Crimson Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65040,
    name: 'Obtained Cerulean Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65050,
    name: 'Obtained Cerulean Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65060,
    name: 'Obtained Speckled Hardtear',
    category: 'crytalTear',
  },
  {
    id: 65070,
    name: 'Obtained Crimson Bubbletear',
    category: 'crytalTear',
  },
  {
    id: 65080,
    name: 'Obtained Opaline Bubbletear',
    category: 'crytalTear',
  },
  {
    id: 65090,
    name: 'Obtained Crimsonburst Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65100,
    name: 'Obtained Greenburst Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65110,
    name: 'Obtained Opaline Hardtear',
    category: 'crytalTear',
  },
  {
    id: 65120,
    name: 'Obtained Winged Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65130,
    name: 'Obtained Thorny Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65140,
    name: 'Obtained Spiked Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65150,
    name: 'Obtained Windy Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65160,
    name: 'Obtained Ruptured Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65170,
    name: 'Obtained Ruptured Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65180,
    name: 'Obtained Leaden Hardtear',
    category: 'crytalTear',
  },
  {
    id: 65190,
    name: 'Obtained Twiggy Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65200,
    name: 'Obtained Crimsonwhorl Bubbletear',
    category: 'crytalTear',
  },
  {
    id: 65210,
    name: 'Obtained Strength-knot Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65220,
    name: 'Obtained Dexterity-knot Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65230,
    name: 'Obtained Intelligence-knot Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65240,
    name: 'Obtained Faith-knot Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65250,
    name: 'Obtained Cerulean Hidden Tear',
    category: 'crytalTear',
  },
  {
    id: 65260,
    name: 'Obtained Stonebarb Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65270,
    name: 'Obtained Purifying Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65280,
    name: 'Obtained Flame-Shrouding Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65290,
    name: 'Obtained Magic-Shrouding Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65300,
    name: 'Obtained Lightning-Shrouding Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65310,
    name: 'Obtained Holy-Shrouding Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65400,
    name: 'Obtained Viridian Hidden Tear',
    category: 'crytalTear',
  },
  {
    id: 65410,
    name: 'Obtained Crimsonburst Dried Tear',
    category: 'crytalTear',
  },
  {
    id: 65420,
    name: 'Obtained Crimson-Sapping Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65430,
    name: 'Obtained Cerulean-Sapping Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65440,
    name: 'Obtained Oil-Soaked Tear',
    category: 'crytalTear',
  },
  {
    id: 65450,
    name: 'Obtained Bloodsucking Cracked Tear',
    category: 'crytalTear',
  },
  {
    id: 65460,
    name: 'Obtained Glovewort Crystal Tear',
    category: 'crytalTear',
  },
  {
    id: 65470,
    name: 'Obtained Deflecting Hardtear',
    category: 'crytalTear',
  },
  {
    id: 65600,
    name: 'Unlock Affinity 0: Standard',
    category: 'affinity',
  },
  {
    id: 65610,
    name: 'Unlock Affinity 1: Heavy',
    category: 'affinity',
  },
  {
    id: 65620,
    name: 'Unlock Affinity 2: Keen',
    category: 'affinity',
  },
  {
    id: 65630,
    name: 'Unlock Affinity 3: Quality',
    category: 'affinity',
  },
  {
    id: 65640,
    name: 'Unlock Affinity 4: Fire',
    category: 'affinity',
  },
  {
    id: 65650,
    name: 'Unlock Affinity 5: Flame Art',
    category: 'affinity',
  },
  {
    id: 65660,
    name: 'Unlock Affinity 6: Lightning',
    category: 'affinity',
  },
  {
    id: 65670,
    name: 'Unlock Affinity 7: Sacred',
    category: 'affinity',
  },
  {
    id: 65680,
    name: 'Unlock Affinity 8: Magic',
    category: 'affinity',
  },
  {
    id: 65690,
    name: 'Unlock Affinity 9: Occult',
    category: 'affinity',
  },
  {
    id: 65700,
    name: 'Unlock Affinity 10: Frost',
    category: 'affinity',
  },
  {
    id: 65710,
    name: 'Unlock Affinity 11: Poison',
    category: 'affinity',
  },
  {
    id: 65720,
    name: 'Unlock Affinity 12: Blood',
    category: 'affinity',
  },
  {
    id: 65800,
    name: 'Acquired Ashes of War: 1 or more',
    category: 'acquiredAshesOfWar',
  },
  {
    id: 65810,
    name: 'Acquired Ash of War: Impaling Thrust',
    category: 'ashOfWar',
  },
  {
    id: 65811,
    name: 'Acquired Ash of War: Piercing Fang',
    category: 'ashOfWar',
  },
  {
    id: 65812,
    name: 'Acquired Ash of War: Spinning Slash',
    category: 'ashOfWar',
  },
  {
    id: 65813,
    name: 'Acquired Ash of War: Repeating Thrust',
    category: 'ashOfWar',
  },
  {
    id: 65814,
    name: 'Acquired Ash of War: Double Slash',
    category: 'ashOfWar',
  },
  {
    id: 65815,
    name: 'Acquired Ash of War: Unsheathe',
    category: 'ashOfWar',
  },
  {
    id: 65816,
    name: 'Acquired Ash of War: Sword Dance',
    category: 'ashOfWar',
  },
  {
    id: 65818,
    name: 'Acquired Ash of War: Quickstep',
    category: 'ashOfWar',
  },
  {
    id: 65819,
    name: "Acquired Ash of War: Bloodhound's Step",
    category: 'ashOfWar',
  },
  {
    id: 65820,
    name: "Acquired Ash of War: Lion's Claw",
    category: 'ashOfWar',
  },
  {
    id: 65821,
    name: 'Acquired Ash of War: Stamp (Upward Cut)',
    category: 'ashOfWar',
  },
  {
    id: 65822,
    name: 'Acquired Ash of War: Stamp (Sweep)',
    category: 'ashOfWar',
  },
  {
    id: 65823,
    name: 'Acquired Ash of War: Wild Strikes',
    category: 'ashOfWar',
  },
  {
    id: 65824,
    name: 'Acquired Ash of War: Earthshaker',
    category: 'ashOfWar',
  },
  {
    id: 65825,
    name: 'Acquired Ash of War: Kick',
    category: 'ashOfWar',
  },
  {
    id: 65826,
    name: 'Acquired Ash of War: Ground Slam',
    category: 'ashOfWar',
  },
  {
    id: 65827,
    name: "Acquired Ash of War: Hoarah Loux's Earthshaker",
    category: 'ashOfWar',
  },
  {
    id: 65828,
    name: 'Acquired Ash of War: Barbaric Roar',
    category: 'ashOfWar',
  },
  {
    id: 65829,
    name: 'Acquired Ash of War: War Cry',
    category: 'ashOfWar',
  },
  {
    id: 65830,
    name: "Acquired Ash of War: Troll's Roar",
    category: 'ashOfWar',
  },
  {
    id: 65831,
    name: "Acquired Ash of War: Braggart's Roar",
    category: 'ashOfWar',
  },
  {
    id: 65832,
    name: 'Acquired Ash of War: Endure',
    category: 'ashOfWar',
  },
  {
    id: 65833,
    name: 'Acquired Ash of War: Charge Forth',
    category: 'ashOfWar',
  },
  {
    id: 65834,
    name: 'Acquired Ash of War: Square Off',
    category: 'ashOfWar',
  },
  {
    id: 65835,
    name: 'Acquired Ash of War: Giant Hunt',
    category: 'ashOfWar',
  },
  {
    id: 65836,
    name: 'Acquired Ash of War: Spinning Strikes',
    category: 'ashOfWar',
  },
  {
    id: 65837,
    name: 'Acquired Ash of War: Storm Assault',
    category: 'ashOfWar',
  },
  {
    id: 65838,
    name: 'Acquired Ash of War: Stormcaller',
    category: 'ashOfWar',
  },
  {
    id: 65839,
    name: 'Acquired Ash of War: Storm Blade',
    category: 'ashOfWar',
  },
  {
    id: 65840,
    name: 'Acquired Ash of War: Vacuum Slice',
    category: 'ashOfWar',
  },
  {
    id: 65841,
    name: 'Acquired Ash of War: Storm Stomp',
    category: 'ashOfWar',
  },
  {
    id: 65842,
    name: 'Acquired Ash of War: Determination',
    category: 'ashOfWar',
  },
  {
    id: 65843,
    name: "Acquired Ash of War: Royal Knight's Resolve",
    category: 'ashOfWar',
  },
  {
    id: 65844,
    name: "Acquired Ash of War: Prelate's Charge",
    category: 'ashOfWar',
  },
  {
    id: 65845,
    name: 'Acquired Ash of War: Eruption',
    category: 'ashOfWar',
  },
  {
    id: 65846,
    name: 'Acquired Ash of War: Flaming Strike',
    category: 'ashOfWar',
  },
  {
    id: 65847,
    name: 'Acquired Ash of War: Black Flame Tornado',
    category: 'ashOfWar',
  },
  {
    id: 65848,
    name: 'Acquired Ash of War: Flame of the Redmanes',
    category: 'ashOfWar',
  },
  {
    id: 65849,
    name: 'Acquired Ash of War: Thunderbolt',
    category: 'ashOfWar',
  },
  {
    id: 65850,
    name: 'Acquired Ash of War: Lightning Slash',
    category: 'ashOfWar',
  },
  {
    id: 65851,
    name: 'Acquired Ash of War: Lightning Ram',
    category: 'ashOfWar',
  },
  {
    id: 65852,
    name: "Acquired Ash of War: Loretta's Slash",
    category: 'ashOfWar',
  },
  {
    id: 65853,
    name: 'Acquired Ash of War: Spinning Weapon',
    category: 'ashOfWar',
  },
  {
    id: 65854,
    name: 'Acquired Ash of War: Glintblade Phalanx',
    category: 'ashOfWar',
  },
  {
    id: 65855,
    name: 'Acquired Ash of War: Glintstone Pebble',
    category: 'ashOfWar',
  },
  {
    id: 65856,
    name: 'Acquired Ash of War: Gravitas',
    category: 'ashOfWar',
  },
  {
    id: 65857,
    name: 'Acquired Ash of War: Carian Grandeur',
    category: 'ashOfWar',
  },
  {
    id: 65858,
    name: 'Acquired Ash of War: Carian Greatsword',
    category: 'ashOfWar',
  },
  {
    id: 65859,
    name: 'Acquired Ash of War: Waves of Darkness',
    category: 'ashOfWar',
  },
  {
    id: 65860,
    name: 'Acquired Ash of War: Cragblade',
    category: 'ashOfWar',
  },
  {
    id: 65861,
    name: 'Acquired Ash of War: Sacred Blade',
    category: 'ashOfWar',
  },
  {
    id: 65862,
    name: 'Acquired Ash of War: Prayerful Strike',
    category: 'ashOfWar',
  },
  {
    id: 65863,
    name: 'Acquired Ash of War: Golden Land',
    category: 'ashOfWar',
  },
  {
    id: 65864,
    name: 'Acquired Ash of War: Sacred Ring of Light',
    category: 'ashOfWar',
  },
  {
    id: 65865,
    name: 'Acquired Ash of War: Golden Slam',
    category: 'ashOfWar',
  },
  {
    id: 65866,
    name: 'Acquired Ash of War: Golden Vow',
    category: 'ashOfWar',
  },
  {
    id: 65867,
    name: 'Acquired Ash of War: Sacred Order',
    category: 'ashOfWar',
  },
  {
    id: 65868,
    name: 'Acquired Ash of War: Shared Order',
    category: 'ashOfWar',
  },
  {
    id: 65869,
    name: "Acquired Ash of War: Beast's Roar",
    category: 'ashOfWar',
  },
  {
    id: 65870,
    name: 'Acquired Ash of War: Phantom Slash',
    category: 'ashOfWar',
  },
  {
    id: 65871,
    name: 'Acquired Ash of War: Spectral Lance',
    category: 'ashOfWar',
  },
  {
    id: 65872,
    name: 'Acquired Ash of War: Raptor of the Mists',
    category: 'ashOfWar',
  },
  {
    id: 65873,
    name: "Acquired Ash of War: White Shadow's Lure",
    category: 'ashOfWar',
  },
  {
    id: 65874,
    name: 'Acquired Ash of War: Poison Moth Flight',
    category: 'ashOfWar',
  },
  {
    id: 65875,
    name: 'Acquired Ash of War: Poisonous Mist',
    category: 'ashOfWar',
  },
  {
    id: 65876,
    name: 'Acquired Ash of War: Blood Tax',
    category: 'ashOfWar',
  },
  {
    id: 65877,
    name: 'Acquired Ash of War: Bloody Slash',
    category: 'ashOfWar',
  },
  {
    id: 65878,
    name: 'Acquired Ash of War: Lifesteal Fist',
    category: 'ashOfWar',
  },
  {
    id: 65879,
    name: 'Acquired Ash of War: Blood Blade',
    category: 'ashOfWar',
  },
  {
    id: 65880,
    name: "Acquired Ash of War: Assassin's Gambit",
    category: 'ashOfWar',
  },
  {
    id: 65881,
    name: 'Acquired Ash of War: Seppuku',
    category: 'ashOfWar',
  },
  {
    id: 65882,
    name: 'Acquired Ash of War: Ice Spear',
    category: 'ashOfWar',
  },
  {
    id: 65883,
    name: 'Acquired Ash of War: Chilling Mist',
    category: 'ashOfWar',
  },
  {
    id: 65884,
    name: 'Acquired Ash of War: Hoarfrost Stomp',
    category: 'ashOfWar',
  },
  {
    id: 65885,
    name: 'Acquired Ash of War: No Skill',
    category: 'ashOfWar',
  },
  {
    id: 65886,
    name: 'Acquired Ash of War: Shield Bash',
    category: 'ashOfWar',
  },
  {
    id: 65887,
    name: 'Acquired Ash of War: Shield Crash',
    category: 'ashOfWar',
  },
  {
    id: 65888,
    name: 'Acquired Ash of War: Barricade Shield',
    category: 'ashOfWar',
  },
  {
    id: 65889,
    name: 'Acquired Ash of War: Parry',
    category: 'ashOfWar',
  },
  {
    id: 65890,
    name: 'Acquired Ash of War: Carian Retaliation',
    category: 'ashOfWar',
  },
  {
    id: 65891,
    name: 'Acquired Ash of War: Storm Wall',
    category: 'ashOfWar',
  },
  {
    id: 65892,
    name: 'Acquired Ash of War: Golden Parry',
    category: 'ashOfWar',
  },
  {
    id: 65893,
    name: "Acquired Ash of War: Thops's Barrier",
    category: 'ashOfWar',
  },
  {
    id: 65894,
    name: 'Acquired Ash of War: Holy Ground',
    category: 'ashOfWar',
  },
  {
    id: 65895,
    name: 'Acquired Ash of War: Vow of the Indomitable',
    category: 'ashOfWar',
  },
  {
    id: 65896,
    name: 'Acquired Ash of War: Barrage',
    category: 'ashOfWar',
  },
  {
    id: 65897,
    name: 'Acquired Ash of War: Mighty Shot',
    category: 'ashOfWar',
  },
  {
    id: 65898,
    name: 'Acquired Ash of War: Sky Shot',
    category: 'ashOfWar',
  },
  {
    id: 65899,
    name: 'Acquired Ash of War: Through and Through',
    category: 'ashOfWar',
  },
  {
    id: 65900,
    name: 'Acquired Ash of War: Enchanted Shot',
    category: 'ashOfWar',
  },
  {
    id: 65901,
    name: 'Acquired Ash of War: Rain of Arrows',
    category: 'ashOfWar',
  },
  {
    id: 65910,
    name: 'Acquired Ash of War: Dryleaf Whirlwind',
    category: 'ashOfWar',
  },
  {
    id: 65911,
    name: 'Acquired Ash of War: Aspects of the Crucible: Wings',
    category: 'ashOfWar',
  },
  {
    id: 65912,
    name: 'Acquired Ash of War: Spinning Gravity Thrust',
    category: 'ashOfWar',
  },
  {
    id: 65913,
    name: 'Acquired Ash of War: Palm Blast',
    category: 'ashOfWar',
  },
  {
    id: 65914,
    name: 'Acquired Ash of War: Piercing Throw',
    category: 'ashOfWar',
  },
  {
    id: 65915,
    name: 'Acquired Ash of War: Scattershot Throw',
    category: 'ashOfWar',
  },
  {
    id: 65916,
    name: 'Acquired Ash of War: Wall of Sparks',
    category: 'ashOfWar',
  },
  {
    id: 65917,
    name: 'Acquired Ash of War: Rolling Sparks',
    category: 'ashOfWar',
  },
  {
    id: 65918,
    name: 'Acquired Ash of War: Raging Beast',
    category: 'ashOfWar',
  },
  {
    id: 65919,
    name: 'Acquired Ash of War: Savage Claws',
    category: 'ashOfWar',
  },
  {
    id: 65920,
    name: 'Acquired Ash of War: Blind Spot',
    category: 'ashOfWar',
  },
  {
    id: 65921,
    name: 'Acquired Ash of War: Swift Slash',
    category: 'ashOfWar',
  },
  {
    id: 65922,
    name: 'Acquired Ash of War: Overhead Stance',
    category: 'ashOfWar',
  },
  {
    id: 65923,
    name: 'Acquired Ash of War: Wing Stance',
    category: 'ashOfWar',
  },
  {
    id: 65924,
    name: 'Acquired Ash of War: Blinkbolt',
    category: 'ashOfWar',
  },
  {
    id: 65925,
    name: 'Acquired Ash of War: Flame Skewer',
    category: 'ashOfWar',
  },
  {
    id: 65926,
    name: "Acquired Ash of War: Savage Lion's Claw",
    category: 'ashOfWar',
  },
  {
    id: 65927,
    name: 'Acquired Ash of War: Divine Beast Frost Stomp',
    category: 'ashOfWar',
  },
  {
    id: 65928,
    name: 'Acquired Ash of War: Flame Spear',
    category: 'ashOfWar',
  },
  {
    id: 65929,
    name: 'Acquired Ash of War: Carian Sovereignty',
    category: 'ashOfWar',
  },
  {
    id: 65930,
    name: 'Acquired Ash of War: Shriek of Sorrow',
    category: 'ashOfWar',
  },
  {
    id: 65931,
    name: 'Acquired Ash of War: Ghostflame Call',
    category: 'ashOfWar',
  },
  {
    id: 65932,
    name: 'Acquired Ash of War: The Poison Flower Blooms Twice',
    category: 'ashOfWar',
  },
  {
    id: 65933,
    name: "Acquired Ash of War: Igon's Drake Hunt",
    category: 'ashOfWar',
  },
  {
    id: 65934,
    name: 'Acquired Ash of War: Shield Strike',
    category: 'ashOfWar',
  },
  {
    id: 66000,
    name: 'Cracked Pot Unlock: 1',
    category: 'crackedPot',
  },
  {
    id: 66010,
    name: 'Cracked Pot Unlock: 2',
    category: 'crackedPot',
  },
  {
    id: 66020,
    name: 'Cracked Pot Unlock: 3',
    category: 'crackedPot',
  },
  {
    id: 66030,
    name: 'Cracked Pot Unlock: 4',
    category: 'crackedPot',
  },
  {
    id: 66040,
    name: 'Cracked Pot Unlock: 5',
    category: 'crackedPot',
  },
  {
    id: 66050,
    name: 'Cracked Pot Unlock: 6',
    category: 'crackedPot',
  },
  {
    id: 66060,
    name: 'Cracked Pot Unlock: 7',
    category: 'crackedPot',
  },
  {
    id: 66070,
    name: 'Cracked Pot Unlock: 8',
    category: 'crackedPot',
  },
  {
    id: 66080,
    name: 'Cracked Pot Unlock: 9',
    category: 'crackedPot',
  },
  {
    id: 66090,
    name: 'Cracked Pot Unlock: 10',
    category: 'crackedPot',
  },
  {
    id: 66100,
    name: 'Cracked Pot Unlock: 11',
    category: 'crackedPot',
  },
  {
    id: 66110,
    name: 'Cracked Pot Unlock: 12',
    category: 'crackedPot',
  },
  {
    id: 66120,
    name: 'Cracked Pot Unlock: 13',
    category: 'crackedPot',
  },
  {
    id: 66130,
    name: 'Cracked Pot Unlock: 14',
    category: 'crackedPot',
  },
  {
    id: 66140,
    name: 'Cracked Pot Unlock: 15',
    category: 'crackedPot',
  },
  {
    id: 66150,
    name: 'Cracked Pot Unlock: 16',
    category: 'crackedPot',
  },
  {
    id: 66160,
    name: 'Cracked Pot Unlock: 17',
    category: 'crackedPot',
  },
  {
    id: 66170,
    name: 'Cracked Pot Unlock: 18',
    category: 'crackedPot',
  },
  {
    id: 66180,
    name: 'Cracked Pot Unlock: 19',
    category: 'crackedPot',
  },
  {
    id: 66190,
    name: 'Cracked Pot Unlock: 20',
    category: 'crackedPot',
  },
  {
    id: 66400,
    name: 'Ritual Pot Unlock: 1',
    category: 'ritualPot',
  },
  {
    id: 66410,
    name: 'Ritual Pot Unlock: 2',
    category: 'ritualPot',
  },
  {
    id: 66420,
    name: 'Ritual Pot Unlock: 3',
    category: 'ritualPot',
  },
  {
    id: 66430,
    name: 'Ritual Pot Unlock: 4',
    category: 'ritualPot',
  },
  {
    id: 66440,
    name: 'Ritual Pot Unlock: 5',
    category: 'ritualPot',
  },
  {
    id: 66450,
    name: 'Ritual Pot Unlock: 6',
    category: 'ritualPot',
  },
  {
    id: 66460,
    name: 'Ritual Pot Unlock: 7',
    category: 'ritualPot',
  },
  {
    id: 66470,
    name: 'Ritual Pot Unlock: 8',
    category: 'ritualPot',
  },
  {
    id: 66480,
    name: 'Ritual Pot Unlock: 9',
    category: 'ritualPot',
  },
  {
    id: 66490,
    name: 'Ritual Pot Unlock: 10',
    category: 'ritualPot',
  },
  {
    id: 66700,
    name: 'Perfume Bottle Unlock: 1',
    category: 'perfumeBottle',
  },
  {
    id: 66710,
    name: 'Perfume Bottle Unlock: 2',
    category: 'perfumeBottle',
  },
  {
    id: 66720,
    name: 'Perfume Bottle Unlock: 3',
    category: 'perfumeBottle',
  },
  {
    id: 66730,
    name: 'Perfume Bottle Unlock: 4',
    category: 'perfumeBottle',
  },
  {
    id: 66740,
    name: 'Perfume Bottle Unlock: 5',
    category: 'perfumeBottle',
  },
  {
    id: 66750,
    name: 'Perfume Bottle Unlock: 6',
    category: 'perfumeBottle',
  },
  {
    id: 66760,
    name: 'Perfume Bottle Unlock: 7',
    category: 'perfumeBottle',
  },
  {
    id: 66770,
    name: 'Perfume Bottle Unlock: 8',
    category: 'perfumeBottle',
  },
  {
    id: 66780,
    name: 'Perfume Bottle Unlock: 9',
    category: 'perfumeBottle',
  },
  {
    id: 66790,
    name: 'Perfume Bottle Unlock: 10',
    category: 'perfumeBottle',
  },
  {
    id: 66900,
    name: 'Hefty Cracked Pot Unlock: 1',
    category: 'crackedPot',
  },
  {
    id: 66910,
    name: 'Hefty Cracked Pot Unlock: 2',
    category: 'crackedPot',
  },
  {
    id: 66920,
    name: 'Hefty Cracked Pot Unlock: 3',
    category: 'crackedPot',
  },
  {
    id: 66930,
    name: 'Hefty Cracked Pot Unlock: 4',
    category: 'crackedPot',
  },
  {
    id: 66940,
    name: 'Hefty Cracked Pot Unlock: 5',
    category: 'crackedPot',
  },
  {
    id: 66950,
    name: 'Hefty Cracked Pot Unlock: 6',
    category: 'crackedPot',
  },
  {
    id: 66960,
    name: 'Hefty Cracked Pot Unlock: 7',
    category: 'crackedPot',
  },
  {
    id: 66970,
    name: 'Hefty Cracked Pot Unlock: 8',
    category: 'crackedPot',
  },
  {
    id: 66980,
    name: 'Hefty Cracked Pot Unlock: 9',
    category: 'crackedPot',
  },
  {
    id: 66990,
    name: 'Hefty Cracked Pot Unlock: 10',
    category: 'crackedPot',
  },
  {
    id: 67000,
    name: "Obtained Nomadic Warrior's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 67010,
    name: "Obtained Nomadic Warrior's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 67020,
    name: "Obtained Nomadic Warrior's Cookbook [6]",
    category: 'cookbook',
  },
  {
    id: 67030,
    name: "Obtained Nomadic Warrior's Cookbook [10]",
    category: 'cookbook',
  },
  {
    id: 67050,
    name: "Obtained Nomadic Warrior's Cookbook [7]",
    category: 'cookbook',
  },
  {
    id: 67060,
    name: "Obtained Nomadic Warrior's Cookbook [12]",
    category: 'cookbook',
  },
  {
    id: 67070,
    name: "Obtained Nomadic Warrior's Cookbook [19]",
    category: 'cookbook',
  },
  {
    id: 67080,
    name: "Obtained Nomadic Warrior's Cookbook [13]",
    category: 'cookbook',
  },
  {
    id: 67090,
    name: "Obtained Nomadic Warrior's Cookbook [23]",
    category: 'cookbook',
  },
  {
    id: 67100,
    name: "Obtained Nomadic Warrior's Cookbook [17]",
    category: 'cookbook',
  },
  {
    id: 67110,
    name: "Obtained Nomadic Warrior's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 67120,
    name: "Obtained Nomadic Warrior's Cookbook [21]",
    category: 'cookbook',
  },
  {
    id: 67130,
    name: "Obtained Missionary's Cookbook [6]",
    category: 'cookbook',
  },
  {
    id: 67200,
    name: "Obtained Armorer's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 67210,
    name: "Obtained Armorer's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 67220,
    name: "Obtained Nomadic Warrior's Cookbook [11]",
    category: 'cookbook',
  },
  {
    id: 67230,
    name: "Obtained Nomadic Warrior's Cookbook [20]",
    category: 'cookbook',
  },
  {
    id: 67250,
    name: "Obtained Armorer's Cookbook [7]",
    category: 'cookbook',
  },
  {
    id: 67260,
    name: "Obtained Armorer's Cookbook [4]",
    category: 'cookbook',
  },
  {
    id: 67270,
    name: "Obtained Nomadic Warrior's Cookbook [18]",
    category: 'cookbook',
  },
  {
    id: 67280,
    name: "Obtained Armorer's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 67290,
    name: "Obtained Nomadic Warrior's Cookbook [16]",
    category: 'cookbook',
  },
  {
    id: 67300,
    name: "Obtained Armorer's Cookbook [6]",
    category: 'cookbook',
  },
  {
    id: 67310,
    name: "Obtained Armorer's Cookbook [5]",
    category: 'cookbook',
  },
  {
    id: 67400,
    name: "Obtained Glintstone Craftsman's Cookbook [4]",
    category: 'cookbook',
  },
  {
    id: 67410,
    name: "Obtained Glintstone Craftsman's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 67420,
    name: "Obtained Glintstone Craftsman's Cookbook [5]",
    category: 'cookbook',
  },
  {
    id: 67430,
    name: "Obtained Nomadic Warrior's Cookbook [9]",
    category: 'cookbook',
  },
  {
    id: 67440,
    name: "Obtained Glintstone Craftsman's Cookbook [8]",
    category: 'cookbook',
  },
  {
    id: 67450,
    name: "Obtained Glintstone Craftsman's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 67460,
    name: "Obtained Glintstone Craftsman's Cookbook [6]",
    category: 'cookbook',
  },
  {
    id: 67470,
    name: "Obtained Glintstone Craftsman's Cookbook [7]",
    category: 'cookbook',
  },
  {
    id: 67480,
    name: "Obtained Glintstone Craftsman's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 67600,
    name: "Obtained Missionary's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 67610,
    name: "Obtained Missionary's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 67630,
    name: "Obtained Missionary's Cookbook [5]",
    category: 'cookbook',
  },
  {
    id: 67640,
    name: "Obtained Missionary's Cookbook [4]",
    category: 'cookbook',
  },
  {
    id: 67650,
    name: "Obtained Missionary's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 67800,
    name: "Obtained Nomadic Warrior's Cookbook [4]",
    category: 'cookbook',
  },
  {
    id: 67830,
    name: "Obtained Nomadic Warrior's Cookbook [5]",
    category: 'cookbook',
  },
  {
    id: 67840,
    name: "Obtained Perfumer's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 67850,
    name: "Obtained Perfumer's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 67860,
    name: "Obtained Perfumer's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 67870,
    name: "Obtained Nomadic Warrior's Cookbook [14]",
    category: 'cookbook',
  },
  {
    id: 67880,
    name: "Obtained Nomadic Warrior's Cookbook [8]",
    category: 'cookbook',
  },
  {
    id: 67890,
    name: "Obtained Nomadic Warrior's Cookbook [22]",
    category: 'cookbook',
  },
  {
    id: 67900,
    name: "Obtained Nomadic Warrior's Cookbook [15]",
    category: 'cookbook',
  },
  {
    id: 67910,
    name: "Obtained Nomadic Warrior's Cookbook [24]",
    category: 'cookbook',
  },
  {
    id: 67920,
    name: "Obtained Perfumer's Cookbook [4]",
    category: 'cookbook',
  },
  {
    id: 68000,
    name: "Obtained Ancient Dragon Apostle's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68010,
    name: "Obtained Ancient Dragon Apostle's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68020,
    name: "Obtained Ancient Dragon Apostle's Cookbook [4]",
    category: 'cookbook',
  },
  {
    id: 68030,
    name: "Obtained Ancient Dragon Apostle's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 68200,
    name: "Obtained Fevor's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68210,
    name: "Obtained Fevor's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 68220,
    name: "Obtained Fevor's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68230,
    name: "Obtained Missionary's Cookbook [7]",
    category: 'cookbook',
  },
  {
    id: 68400,
    name: "Obtained Frenzied's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68410,
    name: "Obtained Frenzied's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68510,
    name: 'Obtained Forager Brood Cookbook [6]',
    category: 'cookbook',
  },
  {
    id: 68520,
    name: 'Obtained Forager Brood Cookbook [1]',
    category: 'cookbook',
  },
  {
    id: 68530,
    name: 'Obtained Forager Brood Cookbook [2]',
    category: 'cookbook',
  },
  {
    id: 68540,
    name: 'Obtained Forager Brood Cookbook [3]',
    category: 'cookbook',
  },
  {
    id: 68550,
    name: 'Obtained Forager Brood Cookbook [4]',
    category: 'cookbook',
  },
  {
    id: 68560,
    name: 'Obtained Forager Brood Cookbook [5]',
    category: 'cookbook',
  },
  {
    id: 68570,
    name: "Obtained Igon's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68580,
    name: "Obtained Finger-Weaver's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68590,
    name: "Obtained Greater Potentate's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68600,
    name: "Obtained Greater Potentate's Cookbook [4]",
    category: 'cookbook',
  },
  {
    id: 68610,
    name: "Obtained Greater Potentate's Cookbook [5]",
    category: 'cookbook',
  },
  {
    id: 68620,
    name: "Obtained Greater Potentate's Cookbook [12]",
    category: 'cookbook',
  },
  {
    id: 68630,
    name: "Obtained Greater Potentate's Cookbook [7]",
    category: 'cookbook',
  },
  {
    id: 68640,
    name: "Obtained Greater Potentate's Cookbook [9]",
    category: 'cookbook',
  },
  {
    id: 68650,
    name: "Obtained Greater Potentate's Cookbook [10]",
    category: 'cookbook',
  },
  {
    id: 68660,
    name: "Obtained Greater Potentate's Cookbook [11]",
    category: 'cookbook',
  },
  {
    id: 68670,
    name: "Obtained Mad Craftsman's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68680,
    name: "Obtained Greater Potentate's Cookbook [8]",
    category: 'cookbook',
  },
  {
    id: 68690,
    name: "Obtained Greater Potentate's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 68700,
    name: "Obtained Greater Potentate's Cookbook [13]",
    category: 'cookbook',
  },
  {
    id: 68710,
    name: "Obtained Greater Potentate's Cookbook [14]",
    category: 'cookbook',
  },
  {
    id: 68720,
    name: "Obtained Greater Potentate's Cookbook [6]",
    category: 'cookbook',
  },
  {
    id: 68730,
    name: "Obtained Greater Potentate's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68740,
    name: "Obtained Ancient Dragon Knight's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68750,
    name: "Obtained Mad Craftsman's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68760,
    name: "Obtained St. Trina Disciple's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68770,
    name: "Obtained Fire Knight's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68780,
    name: "Obtained Ancient Dragon Knight's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68790,
    name: "Obtained Loyal Knight's Cookbook",
    category: 'cookbook',
  },
  {
    id: 68800,
    name: "Obtained Battlefield Priest's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68810,
    name: "Obtained Igon's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68820,
    name: "Obtained Battlefield Priest's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68830,
    name: 'Obtained Forager Brood Cookbook [7]',
    category: 'cookbook',
  },
  {
    id: 68840,
    name: "Obtained St. Trina Disciple's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 68850,
    name: "Obtained Grave Keeper's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68860,
    name: "Obtained Antiquity Scholar's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68870,
    name: "Obtained Tibia's Cookbook",
    category: 'cookbook',
  },
  {
    id: 68880,
    name: "Obtained Mad Craftsman's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 68890,
    name: "Obtained Battlefield Priest's Cookbook [3]",
    category: 'cookbook',
  },
  {
    id: 68900,
    name: "Obtained Fire Knight's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 68910,
    name: "Obtained Antiquity Scholar's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68920,
    name: "Obtained Finger-Weaver's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68930,
    name: "Obtained Battlefield Priest's Cookbook [4]",
    category: 'cookbook',
  },
  {
    id: 68940,
    name: "Obtained Grave Keeper's Cookbook [1]",
    category: 'cookbook',
  },
  {
    id: 68950,
    name: "Obtained St. Trina Disciple's Cookbook [2]",
    category: 'cookbook',
  },
  {
    id: 82001,
    name: 'Display Undergroup Map Option',
    category: 'other',
  },
  {
    id: 10000800,
    name: 'Godrick the Grafted',
    category: 'boss',
    location: 'Stormveil Castle',
  },
  {
    id: 10000850,
    name: 'Margit, the Fell Omen',
    category: 'boss',
    location: 'Stormveil Castle',
  },
  {
    id: 10010800,
    name: 'Grafted Scion',
    category: 'boss',
    location: 'Chapel of Anticipation',
  },
  {
    id: 11000800,
    name: 'Morgott, the Omen King',
    category: 'boss',
    location: 'Leyndell, Royal Capital',
  },
  {
    id: 11000850,
    name: 'Godfrey, First Elden Lord (Golden Shade)',
    category: 'boss',
    location: 'Leyndell, Royal Capital',
  },
  {
    id: 11050800,
    name: 'Godfrey, First Elden Lord / Hoarah Loux, Warrior',
    category: 'boss',
    location: 'Leyndell, Ashen Capital',
  },
  {
    id: 11050850,
    name: 'Sir Gideon Ofnir, the All-Knowing',
    category: 'boss',
    location: 'Leyndell, Ashen Capital',
  },
  {
    id: 12010800,
    name: 'Dragonkin Soldier of Nokstella',
    category: 'boss',
    location: 'Ainsel River',
  },
  {
    id: 12010850,
    name: 'Dragonkin Soldier (Lake of Rot)',
    category: 'boss',
    location: 'Lake of Rot',
  },
  {
    id: 12020800,
    name: 'Valiant Gargoyles',
    category: 'boss',
    location: 'Nokron, Eternal City',
  },
  {
    id: 12020830,
    name: 'Dragonkin Soldier (Siofra River)',
    category: 'boss',
    location: 'Siofra River',
  },
  {
    id: 12020850,
    name: 'Mimic Tear',
    category: 'boss',
    location: 'Nokron, Eternal City',
  },
  {
    id: 12030390,
    name: 'Crucible Knight Siluria',
    category: 'boss',
    location: 'Deeproot Depths',
  },
  {
    id: 12030800,
    name: "Fia's Champions",
    category: 'boss',
    location: 'Deeproot Depths',
  },
  {
    id: 12030850,
    name: 'Lichdragon Fortissax',
    category: 'boss',
    location: 'Deeproot Depths',
  },
  {
    id: 12040800,
    name: 'Astel, Naturalborn of the Void',
    category: 'boss',
    location: 'Grand Cloister',
  },
  {
    id: 12050800,
    name: 'Mohg, Lord of Blood',
    category: 'boss',
    location: 'Mohgwyn Palace',
  },
  {
    id: 12080800,
    name: 'Ancestor Spirit',
    category: 'boss',
    location: 'Siofra River',
  },
  {
    id: 12090800,
    name: 'Regal Ancestor Spirit',
    category: 'boss',
    location: 'Nokron, Eternal City',
  },
  {
    id: 13000800,
    name: 'Beast Clergyman / Maliketh, the Black Blade',
    category: 'boss',
    location: 'Crumbling Farum Azula',
  },
  {
    id: 13000830,
    name: 'Dragonlord Placidusax',
    category: 'boss',
    location: 'Crumbling Farum Azula',
  },
  {
    id: 13000850,
    name: 'Godskin Duo',
    category: 'boss',
    location: 'Crumbling Farum Azula',
  },
  {
    id: 14000800,
    name: 'Rennala, Queen of the Full Moon',
    category: 'boss',
    location: 'Academy of Raya Lucaria',
  },
  {
    id: 14000850,
    name: 'Red Wolf of Radagon',
    category: 'boss',
    location: 'Academy of Raya Lucaria',
  },
  {
    id: 15000800,
    name: 'Malenia, Blade of Miquella',
    category: 'boss',
    location: 'Elphael, Brace of the Haligtree',
  },
  {
    id: 15000850,
    name: 'Loretta, Knight of the Haligtree',
    category: 'boss',
    location: "Miquella's Haligtree",
  },
  {
    id: 16000800,
    name: 'Rykard, Lord of Blasphemy',
    category: 'boss',
    location: 'Volcano Manor',
  },
  {
    id: 16000850,
    name: 'Godskin Noble',
    category: 'boss',
    location: 'Volcano Manor',
  },
  {
    id: 16000860,
    name: 'Abductor Virgins',
    category: 'boss',
    location: 'Volcano Manor',
  },
  {
    id: 18000800,
    name: 'Ulcerated Tree Spirit',
    category: 'boss',
    location: "Fringefolk Hero's Grave",
  },
  {
    id: 18000850,
    name: 'Soldier of Godrick',
    category: 'boss',
    location: 'Cave of Knowledge',
  },
  {
    id: 19000800,
    name: 'Elden Beast',
    category: 'boss',
    location: 'Leyndell, Ashen Capital',
  },
  {
    id: 20000800,
    name: 'Divine Beast Dancing Lion',
    category: 'boss',
    location: 'Belurat, Tower Settlement ',
  },
  {
    id: 20010800,
    name: 'Promised Consort Radahn',
    category: 'boss',
    location: 'Enir-Ilim',
  },
  {
    id: 21000850,
    name: 'Golden Hippopotamus',
    category: 'boss',
    location: 'Shadow Keep',
  },
  {
    id: 21010800,
    name: 'Messmer the Impaler',
    category: 'boss',
    location: 'Shadow Keep',
  },
  {
    id: 22000800,
    name: 'Putrescent Knight',
    category: 'boss',
    location: 'Stone Coffin Fissure',
  },
  {
    id: 25000800,
    name: 'Metyr, Mother of Fingers',
    category: 'boss',
    location: 'Finger Ruins of Miyr',
  },
  {
    id: 28000800,
    name: 'Midra, Lord of Frenzied Flame',
    category: 'boss',
    location: "Midra's Manse",
  },
  {
    id: 30000800,
    name: 'Cemetery Shade',
    category: 'boss',
    location: 'Tombsward Catacombs',
  },
  {
    id: 30010800,
    name: 'Erdtree Burial Watchdog',
    category: 'boss',
    location: "Impaler's Catacombs",
  },
  {
    id: 30020800,
    name: 'Erdtree Burial Watchdog',
    category: 'boss',
    location: 'Stormfoot Catacombs',
  },
  {
    id: 30030800,
    name: 'Spirit-Caller Snail',
    category: 'boss',
    location: "Road's End Catacombs",
  },
  {
    id: 30040800,
    name: 'Grave Warden Duelist',
    category: 'boss',
    location: 'Murkwater Catacombs',
  },
  {
    id: 30050800,
    name: 'Cemetery Shade',
    category: 'boss',
    location: 'Black Knife Catacombs',
  },
  {
    id: 30050850,
    name: 'Black Knife Assassin',
    category: 'boss',
    location: 'Black Knife Catacombs',
  },
  {
    id: 30060800,
    name: 'Erdtree Burial Watchdog',
    category: 'boss',
    location: 'Cliffbottom Catacombs',
  },
  {
    id: 30070800,
    name: 'Erdtree Burial Watchdog',
    category: 'boss',
    location: 'Wyndham Catacombs',
  },
  {
    id: 30080800,
    name: 'Ancient Hero of Zamor',
    category: 'boss',
    location: "Sainted Hero's Grave",
  },
  {
    id: 30090800,
    name: 'Red Wolf of the Champion',
    category: 'boss',
    location: "Gelmir Hero's Grave",
  },
  {
    id: 30100800,
    name: 'Crucible Knight & Crucible Knight Ordovis',
    category: 'boss',
    location: "Azuria Hero's Grave",
  },
  {
    id: 30110800,
    name: 'Black Knife Assassin',
    category: 'boss',
    location: 'Deathtouched Catacombs',
  },
  {
    id: 30120800,
    name: 'Perfumer Tricia & Misbegotten Warrior',
    category: 'boss',
    location: 'Unsightly Catacombs',
  },
  {
    id: 30130800,
    name: 'Grave Warden Duelist',
    category: 'boss',
    location: 'Azuria Side Tomb',
  },
  {
    id: 30140800,
    name: 'Erdtree Burial Watchdog Duo',
    category: 'boss',
    location: 'Minor Erdtree Catacombs',
  },
  {
    id: 30150800,
    name: 'Cemetery Shade',
    category: 'boss',
    location: 'Caelid Catacombs',
  },
  {
    id: 30160800,
    name: 'Putrid Tree Spirit',
    category: 'boss',
    location: 'War-Dead Catacombs',
  },
  {
    id: 30170800,
    name: 'Ancient Hero of Zamor',
    category: 'boss',
    location: "Giant-Conquering Hero's Grave",
  },
  {
    id: 30180800,
    name: 'Ulcerated Tree Spirit',
    category: 'boss',
    location: 'Mountaintop Catacombs',
  },
  {
    id: 30190800,
    name: 'Putrid Grave Warden Duelist',
    category: 'boss',
    location: 'Consecrated Snowfield Catacombs',
  },
  {
    id: 30200800,
    name: 'Stray Mimic Tear',
    category: 'boss',
    location: 'Hidden Path to the Haligtree',
  },
  {
    id: 31000800,
    name: 'Patches',
    category: 'boss',
    location: 'Murkwater Cave',
  },
  {
    id: 31010800,
    name: 'Runebear',
    category: 'boss',
    location: 'Earthbore Cave',
  },
  {
    id: 31020800,
    name: 'Miranda the Blighted Bloom',
    category: 'boss',
    location: 'Tombsward Cave',
  },
  {
    id: 31030800,
    name: 'Beastman of Farum Azula',
    category: 'boss',
    location: 'Groveside Cave',
  },
  {
    id: 31040800,
    name: 'Cleanrot Knight',
    category: 'boss',
    location: 'Stillwater Cave',
  },
  {
    id: 31050800,
    name: 'Bloodhound Knight',
    category: 'boss',
    location: 'Lakeside Crystal Cave',
  },
  {
    id: 31060800,
    name: 'Crystalian Duo',
    category: 'boss',
    location: 'Academy Crystal Cave',
  },
  {
    id: 31070800,
    name: 'Kindred of Rot Duo',
    category: 'boss',
    location: 'Seethewater Cave',
  },
  {
    id: 31090800,
    name: 'Demi-Human Queen Margot',
    category: 'boss',
    location: 'Volcano Cave',
  },
  {
    id: 31100800,
    name: 'Beastman of Farum Azula Duo',
    category: 'boss',
    location: 'Dragonbarrow Cave',
  },
  {
    id: 31110800,
    name: 'Putrid Crystalian Trio',
    category: 'boss',
    location: 'Sellia Hideaway',
  },
  {
    id: 31120800,
    name: 'Misbegotten Crusader',
    category: 'boss',
    location: 'Cave of the Forlorn',
  },
  {
    id: 31150800,
    name: 'Demi-Human Chiefs',
    category: 'boss',
    location: 'Coastal Cave Dungeon',
  },
  {
    id: 31170800,
    name: 'Guardian Golem',
    category: 'boss',
    location: 'Highroad Cave',
  },
  {
    id: 31180800,
    name: 'Omenkiller & Miranda the Blighted Bloom',
    category: 'boss',
    location: "Perfumer's Grotto",
  },
  {
    id: 31190800,
    name: "Black Knife Assassin (Sage's Cave)",
    category: 'boss',
    location: "Sage's Cave",
  },
  {
    id: 31190850,
    name: 'Necromancer Garris',
    category: 'boss',
    location: "Sage's Cave",
  },
  {
    id: 31200800,
    name: 'Cleanrot Knight',
    category: 'boss',
    location: 'Abandoned Cave',
  },
  {
    id: 31210800,
    name: 'Frenzied Duelist',
    category: 'boss',
    location: 'Gaol Cave',
  },
  {
    id: 31220800,
    name: 'Spirit-Caller Snail',
    category: 'boss',
    location: 'Spiritcaller Cave',
  },
  {
    id: 32000800,
    name: 'Scaly Misbegotten',
    category: 'boss',
    location: 'Morne Tunnel',
  },
  {
    id: 32010800,
    name: 'Stonedigger Troll',
    category: 'boss',
    location: 'Limgrave Tunnels',
  },
  {
    id: 32020800,
    name: 'Crystalian',
    category: 'boss',
    location: 'Raya Lucaria Crystal Tunnel',
  },
  {
    id: 32040800,
    name: 'Stonedigger Troll',
    category: 'boss',
    location: 'Old Altus Tunnel',
  },
  {
    id: 32050800,
    name: 'Crystalian Duo',
    category: 'boss',
    location: 'Altus Tunnel',
  },
  {
    id: 32070800,
    name: 'Magma Wyrm',
    category: 'boss',
    location: 'Gael Tunnel',
  },
  {
    id: 32080800,
    name: 'Fallingstar Beast',
    category: 'boss',
    location: 'Sellia Crystal Tunnel',
  },
  {
    id: 32110800,
    name: 'Astel, Stars of Darkness',
    category: 'boss',
    location: 'Yelough Anix Tunnel',
  },
  {
    id: 34120800,
    name: 'Onyx Lord',
    category: 'boss',
    location: 'Sealed Tunnel',
  },
  {
    id: 34130800,
    name: 'Godskin Apostle',
    category: 'boss',
    location: 'Divine Tower of Caelid',
  },
  {
    id: 34140850,
    name: 'Fell Twins',
    category: 'boss',
    location: 'Divine Tower Bridge',
  },
  {
    id: 35000800,
    name: 'Mohg, the Omen',
    category: 'boss',
    location: 'Subterranean Shunning-Grounds',
  },
  {
    id: 35000850,
    name: 'Esgar, Priest of Blood',
    category: 'boss',
    location: 'Leyndell Catacombs',
  },
  {
    id: 39200800,
    name: 'Magma Wyrm Makar',
    category: 'boss',
    location: 'Ruin-Strewn Precipice',
  },
  {
    id: 40000800,
    name: 'Death Knight',
    category: 'boss',
    location: 'Fog Rift Catacombs',
  },
  {
    id: 40010800,
    name: 'Death Knight',
    category: 'boss',
    location: 'Scorpion River Catacombs',
  },
  {
    id: 41000800,
    name: 'Demi-Human Swordmaster Onze',
    category: 'boss',
    location: 'Belurat Gaol',
  },
  {
    id: 41010800,
    name: 'Curseblade Labirith',
    category: 'boss',
    location: 'Bonny Gaol',
  },
  {
    id: 41020800,
    name: 'Lamenter',
    category: 'boss',
    location: "Lamenter's Gaol",
  },
  {
    id: 43000800,
    name: 'Chief Bloodfiend',
    category: 'boss',
    location: 'Rivermouth Cave',
  },
  {
    id: 43010800,
    name: 'Ancient Dragon-Man',
    category: 'boss',
    location: "Dragon's Pit",
  },
  {
    id: 1033420800,
    name: 'Alecto, Black Knife Ringleader',
    category: 'boss',
    location: "Ringleader's Evergaol",
  },
  {
    id: 1033430800,
    name: 'Erdtree Avatar (SW)',
    category: 'boss',
    location: 'Minor Erdtree (Liurnia Southwest)',
  },
  {
    id: 1033450800,
    name: 'Bols, Carian Knight',
    category: 'boss',
    location: "Cuckoo's Evergaol",
  },
  {
    id: 1034420800,
    name: 'Glintstone Dragon Adula',
    category: 'boss',
    location: 'Cathedral of Manus Celes',
  },
  {
    id: 1034450800,
    name: 'Glintstone Dragon Smarag',
    category: 'boss',
    location: 'Liurnia of the Lakes',
  },
  {
    id: 1034480800,
    name: 'Royal Revenant',
    category: 'boss',
    location: 'Kingsrealm Ruins',
  },
  {
    id: 1035420800,
    name: 'Omenkiller',
    category: 'boss',
    location: 'Village of the Albinaurics',
  },
  {
    id: 1035500800,
    name: 'Royal Knight Loretta',
    category: 'boss',
    location: 'Caria Manor',
  },
  {
    id: 1035530800,
    name: 'Magma Wyrm',
    category: 'boss',
    location: 'Mt. Gelmir',
  },
  {
    id: 1036450800,
    name: 'Death Rite Bird',
    category: 'boss',
    location: 'Academy Gate Town',
  },
  {
    id: 1036480800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Liurnia North',
  },
  {
    id: 1036500800,
    name: 'Onyx Lord',
    category: 'boss',
    location: 'Royal Grave Evergaol',
  },
  {
    id: 1036540800,
    name: 'Full-Grown Fallingstar Beast',
    category: 'boss',
    location: 'Mt. Gelmir',
  },
  {
    id: 1037420800,
    name: 'Deathbird',
    category: 'boss',
    location: 'Liurnia of the Lakes',
  },
  {
    id: 1037460800,
    name: 'Bell Bearing Hunter',
    category: 'boss',
    location: 'Church of Vows',
  },
  {
    id: 1037530800,
    name: 'Demi-Human Queen Maggie',
    category: 'boss',
    location: 'Hermit Village',
  },
  {
    id: 1037540810,
    name: 'Ulcerated Tree Spirit',
    category: 'boss',
    location: 'Mt. Gelmir',
  },
  {
    id: 1038410800,
    name: 'Adan, Thief of Fire',
    category: 'boss',
    location: "Malefactor's Evergaol",
  },
  {
    id: 1038480800,
    name: 'Erdtree Avatar (NE)',
    category: 'boss',
    location: 'Minor Erdtree (Liurnia Northeast)',
  },
  {
    id: 1038510800,
    name: 'Demi-Human Queen Gilika',
    category: 'boss',
    location: 'Lux Ruins',
  },
  {
    id: 1038520800,
    name: 'Tibia Mariner',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1039430800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Liurnia South',
  },
  {
    id: 1039440800,
    name: 'Tibia Mariner',
    category: 'boss',
    location: 'Liurnia of the Lakes',
  },
  {
    id: 1039500800,
    name: 'Godefroy the Grafted',
    category: 'boss',
    location: 'Golden Lineage Evergaol',
  },
  {
    id: 1039510800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1039540800,
    name: 'Elemer of the Briar',
    category: 'boss',
    location: 'Shaded Castle',
  },
  {
    id: 1040520800,
    name: "Black Knife Assassin (Sainted Hero's Grave)",
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1040530800,
    name: 'Sanguine Noble',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1041500800,
    name: 'Fallingstar Beast',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1041510800,
    name: 'Tree Sentinel Duo',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1041520800,
    name: 'Ancient Dragon Lansseax',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1041530800,
    name: 'Wormface',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1042330800,
    name: 'Ancient Hero of Zamor',
    category: 'boss',
    location: 'Weeping Evergaol',
  },
  {
    id: 1042360800,
    name: 'Tree Sentinel',
    category: 'boss',
    location: 'Limgrave',
  },
  {
    id: 1042370800,
    name: 'Crucible Knight',
    category: 'boss',
    location: 'Stormhill Evergaol',
  },
  {
    id: 1042380800,
    name: 'Deathbird',
    category: 'boss',
    location: 'Limgrave',
  },
  {
    id: 1042380850,
    name: 'Bell Bearing Hunter',
    category: 'boss',
    location: "Warmaster's Shack",
  },
  {
    id: 1042550800,
    name: 'Godskin Apostle',
    category: 'boss',
    location: 'Windmill Village',
  },
  {
    id: 1043300800,
    name: 'Leonine Misbegotten',
    category: 'boss',
    location: 'Castle Morne',
  },
  {
    id: 1043330800,
    name: 'Erdtree Avatar',
    category: 'boss',
    location: 'Weeping Penisula',
  },
  {
    id: 1043360800,
    name: 'Flying Dragon Agheel',
    category: 'boss',
    location: 'Dragon-Burnt Ruins',
  },
  {
    id: 1043370800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Limgrave',
  },
  {
    id: 1043530800,
    name: 'Bell Bearing Hunter',
    category: 'boss',
    location: "Hermit Merchant's Shack",
  },
  {
    id: 1044320800,
    name: 'Deathbird',
    category: 'boss',
    location: 'Weeping Penisula',
  },
  {
    id: 1044320850,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Weeping Penisula',
  },
  {
    id: 1044350800,
    name: 'Bloodhound Knight Darriwil',
    category: 'boss',
    location: 'Forlorn Hound Evergaol',
  },
  {
    id: 1044360800,
    name: 'Mad Pumpkin Head',
    category: 'boss',
    location: 'Waypoint Ruins',
  },
  {
    id: 1044530800,
    name: 'Deathbird',
    category: 'boss',
    location: 'Altus Plateau',
  },
  {
    id: 1045390800,
    name: 'Tibia Mariner',
    category: 'boss',
    location: 'Summonwater Village',
  },
  {
    id: 1045520800,
    name: 'Draconic Tree Sentinel',
    category: 'boss',
    location: 'Capital Outskirts',
  },
  {
    id: 1047400800,
    name: 'Putrid Avatar',
    category: 'boss',
    location: 'Minor Erdtree (Caelid)',
  },
  {
    id: 1048370800,
    name: 'Decaying Ekzykes',
    category: 'boss',
    location: 'Caelid',
  },
  {
    id: 1048400800,
    name: 'Mad Pumpkin Head Duo',
    category: 'boss',
    location: 'Caelem Ruins',
  },
  {
    id: 1048410800,
    name: 'Bell Bearing Hunter',
    category: 'boss',
    location: "Isolated Merchant's Shack",
  },
  {
    id: 1048510800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Forbidden Lands',
  },
  {
    id: 1048570800,
    name: 'Death Rite Bird',
    category: 'boss',
    location: 'Concecrated Snowfield',
  },
  {
    id: 1049370800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Caelid',
  },
  {
    id: 1049370850,
    name: 'Death Rite Bird',
    category: 'boss',
    location: 'Caelid',
  },
  {
    id: 1049380800,
    name: "Commander O'Neil",
    category: 'boss',
    location: 'Swamp of Aeonia',
  },
  {
    id: 1049390800,
    name: 'Nox Swordstress & Nox Priest',
    category: 'boss',
    location: 'Sellia, Town of Sorcery',
  },
  {
    id: 1049390850,
    name: 'Battlemage Hugues',
    category: 'boss',
    location: 'Sellia Evergaol',
  },
  {
    id: 1049520800,
    name: 'Black Blade Kindred',
    category: 'boss',
    location: 'Forbidden Lands',
  },
  {
    id: 1050560800,
    name: 'Great Wyrm Theodorix',
    category: 'boss',
    location: 'Concecrated Snowfield',
  },
  {
    id: 1050570800,
    name: 'Death Rite Bird',
    category: 'boss',
    location: 'Mountaintops of the Giants',
  },
  {
    id: 1050570850,
    name: 'Putrid Avatar',
    category: 'boss',
    location: 'Minor Erdtree (Consecrated Snowfield)',
  },
  {
    id: 1051360800,
    name: 'Crucible Knight & Misbegotten Warrior',
    category: 'boss',
    location: 'Redmane Castle',
  },
  {
    id: 1051400800,
    name: 'Putrid Avatar',
    category: 'boss',
    location: 'Minor Erdtree (Dragonbarrow)',
  },
  {
    id: 1051430800,
    name: 'Black Blade Kindred',
    category: 'boss',
    location: 'Bestial Sanctum',
  },
  {
    id: 1051570800,
    name: 'Commander Niall',
    category: 'boss',
    location: 'Castle Sol',
  },
  {
    id: 1052410800,
    name: 'Flying Dragon Greyll',
    category: 'boss',
    location: 'Dragonbarrow',
  },
  {
    id: 1052410850,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Dragonbarrow',
  },
  {
    id: 1052560800,
    name: 'Erdtree Avatar',
    category: 'boss',
    location: 'Minor Erdtree (Mountaintops East)',
  },
  {
    id: 1053560800,
    name: 'Roundtable Knight Vyke',
    category: 'boss',
    location: "Lord Contender's Evergaol",
  },
  {
    id: 1248550800,
    name: "Night's Cavalry",
    category: 'boss',
    location: 'Consecrated Snowfield',
  },
  {
    id: 1252380800,
    name: 'Starscourge Radahn',
    category: 'boss',
    location: 'Wailing Dunes',
  },
  {
    id: 1252520800,
    name: 'Fire Giant',
    category: 'boss',
    location: 'Flame Peak',
  },
  {
    id: 1254560800,
    name: 'Borealis the Freezing Fog',
    category: 'boss',
    location: 'Mountaintops of the Giants',
  },
  {
    id: 2044450800,
    name: 'Romina, Saint of the Bud',
    category: 'boss',
    location: 'Church of the Bud',
  },
  {
    id: 2044470800,
    name: 'Rugalea the Great Red Bear',
    category: 'boss',
    location: 'Rauh Base',
  },
  {
    id: 2045440800,
    name: 'Ghostflame Dragon',
    category: 'boss',
    location: 'Gravesite Plain',
  },
  {
    id: 2046380800,
    name: 'Dancer of Ranah',
    category: 'boss',
    location: 'Southern Nameless Mausoleum',
  },
  {
    id: 2046400800,
    name: 'Demi-Human Queen Marigga',
    category: 'boss',
    location: 'Cerulean Coast',
  },
  {
    id: 2046410800,
    name: 'Knight of the Solitary Gaol',
    category: 'boss',
    location: 'Western Nameless Mausoleum',
  },
  {
    id: 2046450800,
    name: 'Red Bear',
    category: 'boss',
    location: 'Northern Nameless Mausoleum',
  },
  {
    id: 2046460800,
    name: 'Divine Beast Dancing Lion',
    category: 'boss',
    location: 'Ancient Ruins of Rauh',
  },
  {
    id: 2047390800,
    name: 'Death Rite Bird',
    category: 'boss',
    location: "Charo's Hidden Grave",
  },
  {
    id: 2047450800,
    name: 'Black Knight Garrew',
    category: 'boss',
    location: 'Fog Rift Fort',
  },
  {
    id: 2048380850,
    name: 'Ghostflame Dragon',
    category: 'boss',
    location: 'Cerulean Coast',
  },
  {
    id: 2048440800,
    name: 'Rellana, Twin Moon Knight',
    category: 'boss',
    location: 'Castle Ensis',
  },
  {
    id: 2049410800,
    name: 'Jagged Peak Drake',
    category: 'boss',
    location: 'Jagged Peak Foothills',
  },
  {
    id: 2049430800,
    name: 'Ghostflame Dragon',
    category: 'boss',
    location: 'Moorth Highway',
  },
  {
    id: 2049430850,
    name: 'Black Knight Edredd',
    category: 'boss',
    location: 'Fort of Reprimand',
  },
  {
    id: 2049440800,
    name: 'Dryleaf Dane',
    category: 'boss',
    location: 'Moorth Ruins',
  },
  {
    id: 2049450800,
    name: 'Ralva the Great Red Bear',
    category: 'boss',
    location: 'Scadu Altus',
  },
  {
    id: 2049480800,
    name: 'Commander Gaius',
    category: 'boss',
    location: 'Scaduview',
  },
  {
    id: 2050470800,
    name: 'Tree Sentinel (Ambush)',
    category: 'boss',
    location: 'Hinterland',
  },
  {
    id: 2050480800,
    name: 'Scadutree Avatar',
    category: 'boss',
    location: 'Scadutree Base',
  },
  {
    id: 2050480860,
    name: 'Tree Sentinel (Exposed)',
    category: 'boss',
    location: 'Hinterland',
  },
  {
    id: 2051440800,
    name: 'Rakshasa',
    category: 'boss',
    location: 'Eastern Nameless Mausoleum',
  },
  {
    id: 2051450800,
    name: 'Count Ymir, Mother of Fingers',
    category: 'boss',
    location: 'Cathedral of Manus Metyr',
  },
  {
    id: 2052400800,
    name: 'Jagged Peak Drake Duo',
    category: 'boss',
    location: 'Jagged Peak',
  },
  {
    id: 2052430800,
    name: 'Jori, Elder Inquisitor',
    category: 'boss',
    location: 'Darklight Catacombs',
  },
  {
    id: 2052480800,
    name: 'Fallingstar Beast',
    category: 'boss',
    location: 'Finger Ruins of Dheo',
  },
  {
    id: 2054390800,
    name: 'Bayle, the Dread',
    category: 'boss',
    location: 'Jagged Peak',
  },
  {
    id: 2054390850,
    name: 'Ancient Dragon Senessax',
    category: 'boss',
    location: 'Jagged Peak',
  },
]
